// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

public interface ControlRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marketdata.ControlRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "bridge_metrics" | "broker_quarantine" | "bridge_event"
   * </pre>
   *
   * <code>string record_type = 1;</code>
   * @return The recordType.
   */
  java.lang.String getRecordType();
  /**
   * <pre>
   * "bridge_metrics" | "broker_quarantine" | "bridge_event"
   * </pre>
   *
   * <code>string record_type = 1;</code>
   * @return The bytes for recordType.
   */
  com.google.protobuf.ByteString
      getRecordTypeBytes();

  /**
   * <pre>
   * Java rejects unknown versions → quarantine
   * </pre>
   *
   * <code>int32 contract_version = 2;</code>
   * @return The contractVersion.
   */
  int getContractVersion();

  /**
   * <code>string event = 3;</code>
   * @return The event.
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 3;</code>
   * @return The bytes for event.
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <code>string slot_id = 4;</code>
   * @return The slotId.
   */
  java.lang.String getSlotId();
  /**
   * <code>string slot_id = 4;</code>
   * @return The bytes for slotId.
   */
  com.google.protobuf.ByteString
      getSlotIdBytes();

  /**
   * <code>string connection_id = 5;</code>
   * @return The connectionId.
   */
  java.lang.String getConnectionId();
  /**
   * <code>string connection_id = 5;</code>
   * @return The bytes for connectionId.
   */
  com.google.protobuf.ByteString
      getConnectionIdBytes();

  /**
   * <code>int64 connection_epoch = 6;</code>
   * @return The connectionEpoch.
   */
  long getConnectionEpoch();

  /**
   * <code>string state = 7;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 7;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int32 assigned_tokens = 8;</code>
   * @return The assignedTokens.
   */
  int getAssignedTokens();

  /**
   * <code>int32 acknowledged_tokens = 9;</code>
   * @return The acknowledgedTokens.
   */
  int getAcknowledgedTokens();

  /**
   * <code>int32 rejected_tokens = 10;</code>
   * @return The rejectedTokens.
   */
  int getRejectedTokens();

  /**
   * <code>string reason = 11;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 11;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>int64 received_ts_ms = 12;</code>
   * @return The receivedTsMs.
   */
  long getReceivedTsMs();

  /**
   * <code>string manifest_fingerprint = 13;</code>
   * @return The manifestFingerprint.
   */
  java.lang.String getManifestFingerprint();
  /**
   * <code>string manifest_fingerprint = 13;</code>
   * @return The bytes for manifestFingerprint.
   */
  com.google.protobuf.ByteString
      getManifestFingerprintBytes();

  /**
   * <pre>
   * slot-identity safety contract
   * </pre>
   *
   * <code>string assigned_token_set_hash = 14;</code>
   * @return The assignedTokenSetHash.
   */
  java.lang.String getAssignedTokenSetHash();
  /**
   * <pre>
   * slot-identity safety contract
   * </pre>
   *
   * <code>string assigned_token_set_hash = 14;</code>
   * @return The bytes for assignedTokenSetHash.
   */
  com.google.protobuf.ByteString
      getAssignedTokenSetHashBytes();

  /**
   * <pre>
   * bridge_metrics extension
   * </pre>
   *
   * <code>int32 reconnect_consecutive = 15;</code>
   * @return The reconnectConsecutive.
   */
  int getReconnectConsecutive();

  /**
   * <code>int32 active_sockets = 16;</code>
   * @return The activeSockets.
   */
  int getActiveSockets();

  /**
   * <code>int32 go_goroutines = 17;</code>
   * @return The goGoroutines.
   */
  int getGoGoroutines();

  /**
   * <code>int64 ts_ms = 18;</code>
   * @return The tsMs.
   */
  long getTsMs();

  /**
   * <pre>
   * broker_quarantine extension
   * </pre>
   *
   * <code>bytes raw_payload = 19;</code>
   * @return The rawPayload.
   */
  com.google.protobuf.ByteString getRawPayload();

  /**
   * <code>string broker_error = 20;</code>
   * @return The brokerError.
   */
  java.lang.String getBrokerError();
  /**
   * <code>string broker_error = 20;</code>
   * @return The bytes for brokerError.
   */
  com.google.protobuf.ByteString
      getBrokerErrorBytes();
}
