// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

/**
 * Protobuf type {@code marketdata.ControlRecord}
 */
public final class ControlRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marketdata.ControlRecord)
    ControlRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ControlRecord.newBuilder() to construct.
  private ControlRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ControlRecord() {
    recordType_ = "";
    event_ = "";
    slotId_ = "";
    connectionId_ = "";
    state_ = "";
    reason_ = "";
    manifestFingerprint_ = "";
    assignedTokenSetHash_ = "";
    rawPayload_ = com.google.protobuf.ByteString.EMPTY;
    brokerError_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ControlRecord();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_ControlRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_ControlRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trading.ingestion.transport.ControlRecord.class, com.trading.ingestion.transport.ControlRecord.Builder.class);
  }

  public static final int RECORD_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recordType_ = "";
  /**
   * <pre>
   * "bridge_metrics" | "broker_quarantine" | "bridge_event"
   * </pre>
   *
   * <code>string record_type = 1;</code>
   * @return The recordType.
   */
  @java.lang.Override
  public java.lang.String getRecordType() {
    java.lang.Object ref = recordType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recordType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "bridge_metrics" | "broker_quarantine" | "bridge_event"
   * </pre>
   *
   * <code>string record_type = 1;</code>
   * @return The bytes for recordType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecordTypeBytes() {
    java.lang.Object ref = recordType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recordType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACT_VERSION_FIELD_NUMBER = 2;
  private int contractVersion_ = 0;
  /**
   * <pre>
   * Java rejects unknown versions → quarantine
   * </pre>
   *
   * <code>int32 contract_version = 2;</code>
   * @return The contractVersion.
   */
  @java.lang.Override
  public int getContractVersion() {
    return contractVersion_;
  }

  public static final int EVENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object event_ = "";
  /**
   * <code>string event = 3;</code>
   * @return The event.
   */
  @java.lang.Override
  public java.lang.String getEvent() {
    java.lang.Object ref = event_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      event_ = s;
      return s;
    }
  }
  /**
   * <code>string event = 3;</code>
   * @return The bytes for event.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventBytes() {
    java.lang.Object ref = event_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      event_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SLOT_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object slotId_ = "";
  /**
   * <code>string slot_id = 4;</code>
   * @return The slotId.
   */
  @java.lang.Override
  public java.lang.String getSlotId() {
    java.lang.Object ref = slotId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      slotId_ = s;
      return s;
    }
  }
  /**
   * <code>string slot_id = 4;</code>
   * @return The bytes for slotId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSlotIdBytes() {
    java.lang.Object ref = slotId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      slotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNECTION_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object connectionId_ = "";
  /**
   * <code>string connection_id = 5;</code>
   * @return The connectionId.
   */
  @java.lang.Override
  public java.lang.String getConnectionId() {
    java.lang.Object ref = connectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connectionId_ = s;
      return s;
    }
  }
  /**
   * <code>string connection_id = 5;</code>
   * @return The bytes for connectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConnectionIdBytes() {
    java.lang.Object ref = connectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNECTION_EPOCH_FIELD_NUMBER = 6;
  private long connectionEpoch_ = 0L;
  /**
   * <code>int64 connection_epoch = 6;</code>
   * @return The connectionEpoch.
   */
  @java.lang.Override
  public long getConnectionEpoch() {
    return connectionEpoch_;
  }

  public static final int STATE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object state_ = "";
  /**
   * <code>string state = 7;</code>
   * @return The state.
   */
  @java.lang.Override
  public java.lang.String getState() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      state_ = s;
      return s;
    }
  }
  /**
   * <code>string state = 7;</code>
   * @return The bytes for state.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateBytes() {
    java.lang.Object ref = state_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      state_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSIGNED_TOKENS_FIELD_NUMBER = 8;
  private int assignedTokens_ = 0;
  /**
   * <code>int32 assigned_tokens = 8;</code>
   * @return The assignedTokens.
   */
  @java.lang.Override
  public int getAssignedTokens() {
    return assignedTokens_;
  }

  public static final int ACKNOWLEDGED_TOKENS_FIELD_NUMBER = 9;
  private int acknowledgedTokens_ = 0;
  /**
   * <code>int32 acknowledged_tokens = 9;</code>
   * @return The acknowledgedTokens.
   */
  @java.lang.Override
  public int getAcknowledgedTokens() {
    return acknowledgedTokens_;
  }

  public static final int REJECTED_TOKENS_FIELD_NUMBER = 10;
  private int rejectedTokens_ = 0;
  /**
   * <code>int32 rejected_tokens = 10;</code>
   * @return The rejectedTokens.
   */
  @java.lang.Override
  public int getRejectedTokens() {
    return rejectedTokens_;
  }

  public static final int REASON_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reason_ = "";
  /**
   * <code>string reason = 11;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reason_ = s;
      return s;
    }
  }
  /**
   * <code>string reason = 11;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    java.lang.Object ref = reason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVED_TS_MS_FIELD_NUMBER = 12;
  private long receivedTsMs_ = 0L;
  /**
   * <code>int64 received_ts_ms = 12;</code>
   * @return The receivedTsMs.
   */
  @java.lang.Override
  public long getReceivedTsMs() {
    return receivedTsMs_;
  }

  public static final int MANIFEST_FINGERPRINT_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object manifestFingerprint_ = "";
  /**
   * <code>string manifest_fingerprint = 13;</code>
   * @return The manifestFingerprint.
   */
  @java.lang.Override
  public java.lang.String getManifestFingerprint() {
    java.lang.Object ref = manifestFingerprint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manifestFingerprint_ = s;
      return s;
    }
  }
  /**
   * <code>string manifest_fingerprint = 13;</code>
   * @return The bytes for manifestFingerprint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getManifestFingerprintBytes() {
    java.lang.Object ref = manifestFingerprint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manifestFingerprint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSIGNED_TOKEN_SET_HASH_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object assignedTokenSetHash_ = "";
  /**
   * <pre>
   * slot-identity safety contract
   * </pre>
   *
   * <code>string assigned_token_set_hash = 14;</code>
   * @return The assignedTokenSetHash.
   */
  @java.lang.Override
  public java.lang.String getAssignedTokenSetHash() {
    java.lang.Object ref = assignedTokenSetHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignedTokenSetHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * slot-identity safety contract
   * </pre>
   *
   * <code>string assigned_token_set_hash = 14;</code>
   * @return The bytes for assignedTokenSetHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssignedTokenSetHashBytes() {
    java.lang.Object ref = assignedTokenSetHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignedTokenSetHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECONNECT_CONSECUTIVE_FIELD_NUMBER = 15;
  private int reconnectConsecutive_ = 0;
  /**
   * <pre>
   * bridge_metrics extension
   * </pre>
   *
   * <code>int32 reconnect_consecutive = 15;</code>
   * @return The reconnectConsecutive.
   */
  @java.lang.Override
  public int getReconnectConsecutive() {
    return reconnectConsecutive_;
  }

  public static final int ACTIVE_SOCKETS_FIELD_NUMBER = 16;
  private int activeSockets_ = 0;
  /**
   * <code>int32 active_sockets = 16;</code>
   * @return The activeSockets.
   */
  @java.lang.Override
  public int getActiveSockets() {
    return activeSockets_;
  }

  public static final int GO_GOROUTINES_FIELD_NUMBER = 17;
  private int goGoroutines_ = 0;
  /**
   * <code>int32 go_goroutines = 17;</code>
   * @return The goGoroutines.
   */
  @java.lang.Override
  public int getGoGoroutines() {
    return goGoroutines_;
  }

  public static final int TS_MS_FIELD_NUMBER = 18;
  private long tsMs_ = 0L;
  /**
   * <code>int64 ts_ms = 18;</code>
   * @return The tsMs.
   */
  @java.lang.Override
  public long getTsMs() {
    return tsMs_;
  }

  public static final int RAW_PAYLOAD_FIELD_NUMBER = 19;
  private com.google.protobuf.ByteString rawPayload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * broker_quarantine extension
   * </pre>
   *
   * <code>bytes raw_payload = 19;</code>
   * @return The rawPayload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRawPayload() {
    return rawPayload_;
  }

  public static final int BROKER_ERROR_FIELD_NUMBER = 20;
  @SuppressWarnings("serial")
  private volatile java.lang.Object brokerError_ = "";
  /**
   * <code>string broker_error = 20;</code>
   * @return The brokerError.
   */
  @java.lang.Override
  public java.lang.String getBrokerError() {
    java.lang.Object ref = brokerError_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brokerError_ = s;
      return s;
    }
  }
  /**
   * <code>string broker_error = 20;</code>
   * @return The bytes for brokerError.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrokerErrorBytes() {
    java.lang.Object ref = brokerError_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brokerError_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recordType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, recordType_);
    }
    if (contractVersion_ != 0) {
      output.writeInt32(2, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(event_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, event_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, slotId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, connectionId_);
    }
    if (connectionEpoch_ != 0L) {
      output.writeInt64(6, connectionEpoch_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, state_);
    }
    if (assignedTokens_ != 0) {
      output.writeInt32(8, assignedTokens_);
    }
    if (acknowledgedTokens_ != 0) {
      output.writeInt32(9, acknowledgedTokens_);
    }
    if (rejectedTokens_ != 0) {
      output.writeInt32(10, rejectedTokens_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, reason_);
    }
    if (receivedTsMs_ != 0L) {
      output.writeInt64(12, receivedTsMs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(manifestFingerprint_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, manifestFingerprint_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedTokenSetHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, assignedTokenSetHash_);
    }
    if (reconnectConsecutive_ != 0) {
      output.writeInt32(15, reconnectConsecutive_);
    }
    if (activeSockets_ != 0) {
      output.writeInt32(16, activeSockets_);
    }
    if (goGoroutines_ != 0) {
      output.writeInt32(17, goGoroutines_);
    }
    if (tsMs_ != 0L) {
      output.writeInt64(18, tsMs_);
    }
    if (!rawPayload_.isEmpty()) {
      output.writeBytes(19, rawPayload_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brokerError_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 20, brokerError_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recordType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, recordType_);
    }
    if (contractVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, contractVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(event_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, event_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(slotId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, slotId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, connectionId_);
    }
    if (connectionEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, connectionEpoch_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, state_);
    }
    if (assignedTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, assignedTokens_);
    }
    if (acknowledgedTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, acknowledgedTokens_);
    }
    if (rejectedTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, rejectedTokens_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, reason_);
    }
    if (receivedTsMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, receivedTsMs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(manifestFingerprint_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, manifestFingerprint_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(assignedTokenSetHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, assignedTokenSetHash_);
    }
    if (reconnectConsecutive_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, reconnectConsecutive_);
    }
    if (activeSockets_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, activeSockets_);
    }
    if (goGoroutines_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, goGoroutines_);
    }
    if (tsMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(18, tsMs_);
    }
    if (!rawPayload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(19, rawPayload_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(brokerError_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(20, brokerError_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trading.ingestion.transport.ControlRecord)) {
      return super.equals(obj);
    }
    com.trading.ingestion.transport.ControlRecord other = (com.trading.ingestion.transport.ControlRecord) obj;

    if (!getRecordType()
        .equals(other.getRecordType())) return false;
    if (getContractVersion()
        != other.getContractVersion()) return false;
    if (!getEvent()
        .equals(other.getEvent())) return false;
    if (!getSlotId()
        .equals(other.getSlotId())) return false;
    if (!getConnectionId()
        .equals(other.getConnectionId())) return false;
    if (getConnectionEpoch()
        != other.getConnectionEpoch()) return false;
    if (!getState()
        .equals(other.getState())) return false;
    if (getAssignedTokens()
        != other.getAssignedTokens()) return false;
    if (getAcknowledgedTokens()
        != other.getAcknowledgedTokens()) return false;
    if (getRejectedTokens()
        != other.getRejectedTokens()) return false;
    if (!getReason()
        .equals(other.getReason())) return false;
    if (getReceivedTsMs()
        != other.getReceivedTsMs()) return false;
    if (!getManifestFingerprint()
        .equals(other.getManifestFingerprint())) return false;
    if (!getAssignedTokenSetHash()
        .equals(other.getAssignedTokenSetHash())) return false;
    if (getReconnectConsecutive()
        != other.getReconnectConsecutive()) return false;
    if (getActiveSockets()
        != other.getActiveSockets()) return false;
    if (getGoGoroutines()
        != other.getGoGoroutines()) return false;
    if (getTsMs()
        != other.getTsMs()) return false;
    if (!getRawPayload()
        .equals(other.getRawPayload())) return false;
    if (!getBrokerError()
        .equals(other.getBrokerError())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECORD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRecordType().hashCode();
    hash = (37 * hash) + CONTRACT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getContractVersion();
    hash = (37 * hash) + EVENT_FIELD_NUMBER;
    hash = (53 * hash) + getEvent().hashCode();
    hash = (37 * hash) + SLOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSlotId().hashCode();
    hash = (37 * hash) + CONNECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConnectionId().hashCode();
    hash = (37 * hash) + CONNECTION_EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getConnectionEpoch());
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + getState().hashCode();
    hash = (37 * hash) + ASSIGNED_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getAssignedTokens();
    hash = (37 * hash) + ACKNOWLEDGED_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getAcknowledgedTokens();
    hash = (37 * hash) + REJECTED_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getRejectedTokens();
    hash = (37 * hash) + REASON_FIELD_NUMBER;
    hash = (53 * hash) + getReason().hashCode();
    hash = (37 * hash) + RECEIVED_TS_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceivedTsMs());
    hash = (37 * hash) + MANIFEST_FINGERPRINT_FIELD_NUMBER;
    hash = (53 * hash) + getManifestFingerprint().hashCode();
    hash = (37 * hash) + ASSIGNED_TOKEN_SET_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getAssignedTokenSetHash().hashCode();
    hash = (37 * hash) + RECONNECT_CONSECUTIVE_FIELD_NUMBER;
    hash = (53 * hash) + getReconnectConsecutive();
    hash = (37 * hash) + ACTIVE_SOCKETS_FIELD_NUMBER;
    hash = (53 * hash) + getActiveSockets();
    hash = (37 * hash) + GO_GOROUTINES_FIELD_NUMBER;
    hash = (53 * hash) + getGoGoroutines();
    hash = (37 * hash) + TS_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTsMs());
    hash = (37 * hash) + RAW_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getRawPayload().hashCode();
    hash = (37 * hash) + BROKER_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getBrokerError().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trading.ingestion.transport.ControlRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.ControlRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.ControlRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trading.ingestion.transport.ControlRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marketdata.ControlRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marketdata.ControlRecord)
      com.trading.ingestion.transport.ControlRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_ControlRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_ControlRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trading.ingestion.transport.ControlRecord.class, com.trading.ingestion.transport.ControlRecord.Builder.class);
    }

    // Construct using com.trading.ingestion.transport.ControlRecord.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      recordType_ = "";
      contractVersion_ = 0;
      event_ = "";
      slotId_ = "";
      connectionId_ = "";
      connectionEpoch_ = 0L;
      state_ = "";
      assignedTokens_ = 0;
      acknowledgedTokens_ = 0;
      rejectedTokens_ = 0;
      reason_ = "";
      receivedTsMs_ = 0L;
      manifestFingerprint_ = "";
      assignedTokenSetHash_ = "";
      reconnectConsecutive_ = 0;
      activeSockets_ = 0;
      goGoroutines_ = 0;
      tsMs_ = 0L;
      rawPayload_ = com.google.protobuf.ByteString.EMPTY;
      brokerError_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_ControlRecord_descriptor;
    }

    @java.lang.Override
    public com.trading.ingestion.transport.ControlRecord getDefaultInstanceForType() {
      return com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
    }

    @java.lang.Override
    public com.trading.ingestion.transport.ControlRecord build() {
      com.trading.ingestion.transport.ControlRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trading.ingestion.transport.ControlRecord buildPartial() {
      com.trading.ingestion.transport.ControlRecord result = new com.trading.ingestion.transport.ControlRecord(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.trading.ingestion.transport.ControlRecord result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.recordType_ = recordType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contractVersion_ = contractVersion_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.event_ = event_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.slotId_ = slotId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.connectionId_ = connectionId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.connectionEpoch_ = connectionEpoch_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.assignedTokens_ = assignedTokens_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.acknowledgedTokens_ = acknowledgedTokens_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.rejectedTokens_ = rejectedTokens_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.reason_ = reason_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.receivedTsMs_ = receivedTsMs_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.manifestFingerprint_ = manifestFingerprint_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.assignedTokenSetHash_ = assignedTokenSetHash_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.reconnectConsecutive_ = reconnectConsecutive_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.activeSockets_ = activeSockets_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.goGoroutines_ = goGoroutines_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.tsMs_ = tsMs_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.rawPayload_ = rawPayload_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.brokerError_ = brokerError_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trading.ingestion.transport.ControlRecord) {
        return mergeFrom((com.trading.ingestion.transport.ControlRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trading.ingestion.transport.ControlRecord other) {
      if (other == com.trading.ingestion.transport.ControlRecord.getDefaultInstance()) return this;
      if (!other.getRecordType().isEmpty()) {
        recordType_ = other.recordType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getContractVersion() != 0) {
        setContractVersion(other.getContractVersion());
      }
      if (!other.getEvent().isEmpty()) {
        event_ = other.event_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSlotId().isEmpty()) {
        slotId_ = other.slotId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getConnectionId().isEmpty()) {
        connectionId_ = other.connectionId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getConnectionEpoch() != 0L) {
        setConnectionEpoch(other.getConnectionEpoch());
      }
      if (!other.getState().isEmpty()) {
        state_ = other.state_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getAssignedTokens() != 0) {
        setAssignedTokens(other.getAssignedTokens());
      }
      if (other.getAcknowledgedTokens() != 0) {
        setAcknowledgedTokens(other.getAcknowledgedTokens());
      }
      if (other.getRejectedTokens() != 0) {
        setRejectedTokens(other.getRejectedTokens());
      }
      if (!other.getReason().isEmpty()) {
        reason_ = other.reason_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.getReceivedTsMs() != 0L) {
        setReceivedTsMs(other.getReceivedTsMs());
      }
      if (!other.getManifestFingerprint().isEmpty()) {
        manifestFingerprint_ = other.manifestFingerprint_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getAssignedTokenSetHash().isEmpty()) {
        assignedTokenSetHash_ = other.assignedTokenSetHash_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (other.getReconnectConsecutive() != 0) {
        setReconnectConsecutive(other.getReconnectConsecutive());
      }
      if (other.getActiveSockets() != 0) {
        setActiveSockets(other.getActiveSockets());
      }
      if (other.getGoGoroutines() != 0) {
        setGoGoroutines(other.getGoGoroutines());
      }
      if (other.getTsMs() != 0L) {
        setTsMs(other.getTsMs());
      }
      if (other.getRawPayload() != com.google.protobuf.ByteString.EMPTY) {
        setRawPayload(other.getRawPayload());
      }
      if (!other.getBrokerError().isEmpty()) {
        brokerError_ = other.brokerError_;
        bitField0_ |= 0x00080000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              recordType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              contractVersion_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              event_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              slotId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              connectionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              connectionEpoch_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              state_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              assignedTokens_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              acknowledgedTokens_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              rejectedTokens_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              reason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              receivedTsMs_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 106: {
              manifestFingerprint_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              assignedTokenSetHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 120: {
              reconnectConsecutive_ = input.readInt32();
              bitField0_ |= 0x00004000;
              break;
            } // case 120
            case 128: {
              activeSockets_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            case 136: {
              goGoroutines_ = input.readInt32();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            case 144: {
              tsMs_ = input.readInt64();
              bitField0_ |= 0x00020000;
              break;
            } // case 144
            case 154: {
              rawPayload_ = input.readBytes();
              bitField0_ |= 0x00040000;
              break;
            } // case 154
            case 162: {
              brokerError_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00080000;
              break;
            } // case 162
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object recordType_ = "";
    /**
     * <pre>
     * "bridge_metrics" | "broker_quarantine" | "bridge_event"
     * </pre>
     *
     * <code>string record_type = 1;</code>
     * @return The recordType.
     */
    public java.lang.String getRecordType() {
      java.lang.Object ref = recordType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "bridge_metrics" | "broker_quarantine" | "bridge_event"
     * </pre>
     *
     * <code>string record_type = 1;</code>
     * @return The bytes for recordType.
     */
    public com.google.protobuf.ByteString
        getRecordTypeBytes() {
      java.lang.Object ref = recordType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "bridge_metrics" | "broker_quarantine" | "bridge_event"
     * </pre>
     *
     * <code>string record_type = 1;</code>
     * @param value The recordType to set.
     * @return This builder for chaining.
     */
    public Builder setRecordType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recordType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "bridge_metrics" | "broker_quarantine" | "bridge_event"
     * </pre>
     *
     * <code>string record_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecordType() {
      recordType_ = getDefaultInstance().getRecordType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "bridge_metrics" | "broker_quarantine" | "bridge_event"
     * </pre>
     *
     * <code>string record_type = 1;</code>
     * @param value The bytes for recordType to set.
     * @return This builder for chaining.
     */
    public Builder setRecordTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recordType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int contractVersion_ ;
    /**
     * <pre>
     * Java rejects unknown versions → quarantine
     * </pre>
     *
     * <code>int32 contract_version = 2;</code>
     * @return The contractVersion.
     */
    @java.lang.Override
    public int getContractVersion() {
      return contractVersion_;
    }
    /**
     * <pre>
     * Java rejects unknown versions → quarantine
     * </pre>
     *
     * <code>int32 contract_version = 2;</code>
     * @param value The contractVersion to set.
     * @return This builder for chaining.
     */
    public Builder setContractVersion(int value) {
      
      contractVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Java rejects unknown versions → quarantine
     * </pre>
     *
     * <code>int32 contract_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      contractVersion_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object event_ = "";
    /**
     * <code>string event = 3;</code>
     * @return The event.
     */
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event = 3;</code>
     * @return The bytes for event.
     */
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event = 3;</code>
     * @param value The event to set.
     * @return This builder for chaining.
     */
    public Builder setEvent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      event_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string event = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvent() {
      event_ = getDefaultInstance().getEvent();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string event = 3;</code>
     * @param value The bytes for event to set.
     * @return This builder for chaining.
     */
    public Builder setEventBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      event_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object slotId_ = "";
    /**
     * <code>string slot_id = 4;</code>
     * @return The slotId.
     */
    public java.lang.String getSlotId() {
      java.lang.Object ref = slotId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        slotId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string slot_id = 4;</code>
     * @return The bytes for slotId.
     */
    public com.google.protobuf.ByteString
        getSlotIdBytes() {
      java.lang.Object ref = slotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        slotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string slot_id = 4;</code>
     * @param value The slotId to set.
     * @return This builder for chaining.
     */
    public Builder setSlotId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      slotId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string slot_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlotId() {
      slotId_ = getDefaultInstance().getSlotId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string slot_id = 4;</code>
     * @param value The bytes for slotId to set.
     * @return This builder for chaining.
     */
    public Builder setSlotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      slotId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object connectionId_ = "";
    /**
     * <code>string connection_id = 5;</code>
     * @return The connectionId.
     */
    public java.lang.String getConnectionId() {
      java.lang.Object ref = connectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string connection_id = 5;</code>
     * @return The bytes for connectionId.
     */
    public com.google.protobuf.ByteString
        getConnectionIdBytes() {
      java.lang.Object ref = connectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string connection_id = 5;</code>
     * @param value The connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      connectionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string connection_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionId() {
      connectionId_ = getDefaultInstance().getConnectionId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string connection_id = 5;</code>
     * @param value The bytes for connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      connectionId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long connectionEpoch_ ;
    /**
     * <code>int64 connection_epoch = 6;</code>
     * @return The connectionEpoch.
     */
    @java.lang.Override
    public long getConnectionEpoch() {
      return connectionEpoch_;
    }
    /**
     * <code>int64 connection_epoch = 6;</code>
     * @param value The connectionEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionEpoch(long value) {
      
      connectionEpoch_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 connection_epoch = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionEpoch() {
      bitField0_ = (bitField0_ & ~0x00000020);
      connectionEpoch_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object state_ = "";
    /**
     * <code>string state = 7;</code>
     * @return The state.
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state = 7;</code>
     * @return The bytes for state.
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state = 7;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      state_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string state = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      state_ = getDefaultInstance().getState();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string state = 7;</code>
     * @param value The bytes for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      state_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int assignedTokens_ ;
    /**
     * <code>int32 assigned_tokens = 8;</code>
     * @return The assignedTokens.
     */
    @java.lang.Override
    public int getAssignedTokens() {
      return assignedTokens_;
    }
    /**
     * <code>int32 assigned_tokens = 8;</code>
     * @param value The assignedTokens to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedTokens(int value) {
      
      assignedTokens_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 assigned_tokens = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignedTokens() {
      bitField0_ = (bitField0_ & ~0x00000080);
      assignedTokens_ = 0;
      onChanged();
      return this;
    }

    private int acknowledgedTokens_ ;
    /**
     * <code>int32 acknowledged_tokens = 9;</code>
     * @return The acknowledgedTokens.
     */
    @java.lang.Override
    public int getAcknowledgedTokens() {
      return acknowledgedTokens_;
    }
    /**
     * <code>int32 acknowledged_tokens = 9;</code>
     * @param value The acknowledgedTokens to set.
     * @return This builder for chaining.
     */
    public Builder setAcknowledgedTokens(int value) {
      
      acknowledgedTokens_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 acknowledged_tokens = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcknowledgedTokens() {
      bitField0_ = (bitField0_ & ~0x00000100);
      acknowledgedTokens_ = 0;
      onChanged();
      return this;
    }

    private int rejectedTokens_ ;
    /**
     * <code>int32 rejected_tokens = 10;</code>
     * @return The rejectedTokens.
     */
    @java.lang.Override
    public int getRejectedTokens() {
      return rejectedTokens_;
    }
    /**
     * <code>int32 rejected_tokens = 10;</code>
     * @param value The rejectedTokens to set.
     * @return This builder for chaining.
     */
    public Builder setRejectedTokens(int value) {
      
      rejectedTokens_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rejected_tokens = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRejectedTokens() {
      bitField0_ = (bitField0_ & ~0x00000200);
      rejectedTokens_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reason_ = "";
    /**
     * <code>string reason = 11;</code>
     * @return The reason.
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reason = 11;</code>
     * @return The bytes for reason.
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reason = 11;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reason_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string reason = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      reason_ = getDefaultInstance().getReason();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string reason = 11;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reason_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private long receivedTsMs_ ;
    /**
     * <code>int64 received_ts_ms = 12;</code>
     * @return The receivedTsMs.
     */
    @java.lang.Override
    public long getReceivedTsMs() {
      return receivedTsMs_;
    }
    /**
     * <code>int64 received_ts_ms = 12;</code>
     * @param value The receivedTsMs to set.
     * @return This builder for chaining.
     */
    public Builder setReceivedTsMs(long value) {
      
      receivedTsMs_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int64 received_ts_ms = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceivedTsMs() {
      bitField0_ = (bitField0_ & ~0x00000800);
      receivedTsMs_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object manifestFingerprint_ = "";
    /**
     * <code>string manifest_fingerprint = 13;</code>
     * @return The manifestFingerprint.
     */
    public java.lang.String getManifestFingerprint() {
      java.lang.Object ref = manifestFingerprint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manifestFingerprint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string manifest_fingerprint = 13;</code>
     * @return The bytes for manifestFingerprint.
     */
    public com.google.protobuf.ByteString
        getManifestFingerprintBytes() {
      java.lang.Object ref = manifestFingerprint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manifestFingerprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string manifest_fingerprint = 13;</code>
     * @param value The manifestFingerprint to set.
     * @return This builder for chaining.
     */
    public Builder setManifestFingerprint(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      manifestFingerprint_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string manifest_fingerprint = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearManifestFingerprint() {
      manifestFingerprint_ = getDefaultInstance().getManifestFingerprint();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string manifest_fingerprint = 13;</code>
     * @param value The bytes for manifestFingerprint to set.
     * @return This builder for chaining.
     */
    public Builder setManifestFingerprintBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      manifestFingerprint_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object assignedTokenSetHash_ = "";
    /**
     * <pre>
     * slot-identity safety contract
     * </pre>
     *
     * <code>string assigned_token_set_hash = 14;</code>
     * @return The assignedTokenSetHash.
     */
    public java.lang.String getAssignedTokenSetHash() {
      java.lang.Object ref = assignedTokenSetHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignedTokenSetHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * slot-identity safety contract
     * </pre>
     *
     * <code>string assigned_token_set_hash = 14;</code>
     * @return The bytes for assignedTokenSetHash.
     */
    public com.google.protobuf.ByteString
        getAssignedTokenSetHashBytes() {
      java.lang.Object ref = assignedTokenSetHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignedTokenSetHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * slot-identity safety contract
     * </pre>
     *
     * <code>string assigned_token_set_hash = 14;</code>
     * @param value The assignedTokenSetHash to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedTokenSetHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      assignedTokenSetHash_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * slot-identity safety contract
     * </pre>
     *
     * <code>string assigned_token_set_hash = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignedTokenSetHash() {
      assignedTokenSetHash_ = getDefaultInstance().getAssignedTokenSetHash();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * slot-identity safety contract
     * </pre>
     *
     * <code>string assigned_token_set_hash = 14;</code>
     * @param value The bytes for assignedTokenSetHash to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedTokenSetHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      assignedTokenSetHash_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private int reconnectConsecutive_ ;
    /**
     * <pre>
     * bridge_metrics extension
     * </pre>
     *
     * <code>int32 reconnect_consecutive = 15;</code>
     * @return The reconnectConsecutive.
     */
    @java.lang.Override
    public int getReconnectConsecutive() {
      return reconnectConsecutive_;
    }
    /**
     * <pre>
     * bridge_metrics extension
     * </pre>
     *
     * <code>int32 reconnect_consecutive = 15;</code>
     * @param value The reconnectConsecutive to set.
     * @return This builder for chaining.
     */
    public Builder setReconnectConsecutive(int value) {
      
      reconnectConsecutive_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * bridge_metrics extension
     * </pre>
     *
     * <code>int32 reconnect_consecutive = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearReconnectConsecutive() {
      bitField0_ = (bitField0_ & ~0x00004000);
      reconnectConsecutive_ = 0;
      onChanged();
      return this;
    }

    private int activeSockets_ ;
    /**
     * <code>int32 active_sockets = 16;</code>
     * @return The activeSockets.
     */
    @java.lang.Override
    public int getActiveSockets() {
      return activeSockets_;
    }
    /**
     * <code>int32 active_sockets = 16;</code>
     * @param value The activeSockets to set.
     * @return This builder for chaining.
     */
    public Builder setActiveSockets(int value) {
      
      activeSockets_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 active_sockets = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearActiveSockets() {
      bitField0_ = (bitField0_ & ~0x00008000);
      activeSockets_ = 0;
      onChanged();
      return this;
    }

    private int goGoroutines_ ;
    /**
     * <code>int32 go_goroutines = 17;</code>
     * @return The goGoroutines.
     */
    @java.lang.Override
    public int getGoGoroutines() {
      return goGoroutines_;
    }
    /**
     * <code>int32 go_goroutines = 17;</code>
     * @param value The goGoroutines to set.
     * @return This builder for chaining.
     */
    public Builder setGoGoroutines(int value) {
      
      goGoroutines_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 go_goroutines = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoGoroutines() {
      bitField0_ = (bitField0_ & ~0x00010000);
      goGoroutines_ = 0;
      onChanged();
      return this;
    }

    private long tsMs_ ;
    /**
     * <code>int64 ts_ms = 18;</code>
     * @return The tsMs.
     */
    @java.lang.Override
    public long getTsMs() {
      return tsMs_;
    }
    /**
     * <code>int64 ts_ms = 18;</code>
     * @param value The tsMs to set.
     * @return This builder for chaining.
     */
    public Builder setTsMs(long value) {
      
      tsMs_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ts_ms = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearTsMs() {
      bitField0_ = (bitField0_ & ~0x00020000);
      tsMs_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rawPayload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * broker_quarantine extension
     * </pre>
     *
     * <code>bytes raw_payload = 19;</code>
     * @return The rawPayload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawPayload() {
      return rawPayload_;
    }
    /**
     * <pre>
     * broker_quarantine extension
     * </pre>
     *
     * <code>bytes raw_payload = 19;</code>
     * @param value The rawPayload to set.
     * @return This builder for chaining.
     */
    public Builder setRawPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      rawPayload_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * broker_quarantine extension
     * </pre>
     *
     * <code>bytes raw_payload = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawPayload() {
      bitField0_ = (bitField0_ & ~0x00040000);
      rawPayload_ = getDefaultInstance().getRawPayload();
      onChanged();
      return this;
    }

    private java.lang.Object brokerError_ = "";
    /**
     * <code>string broker_error = 20;</code>
     * @return The brokerError.
     */
    public java.lang.String getBrokerError() {
      java.lang.Object ref = brokerError_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brokerError_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string broker_error = 20;</code>
     * @return The bytes for brokerError.
     */
    public com.google.protobuf.ByteString
        getBrokerErrorBytes() {
      java.lang.Object ref = brokerError_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string broker_error = 20;</code>
     * @param value The brokerError to set.
     * @return This builder for chaining.
     */
    public Builder setBrokerError(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      brokerError_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <code>string broker_error = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrokerError() {
      brokerError_ = getDefaultInstance().getBrokerError();
      bitField0_ = (bitField0_ & ~0x00080000);
      onChanged();
      return this;
    }
    /**
     * <code>string broker_error = 20;</code>
     * @param value The bytes for brokerError to set.
     * @return This builder for chaining.
     */
    public Builder setBrokerErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      brokerError_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marketdata.ControlRecord)
  }

  // @@protoc_insertion_point(class_scope:marketdata.ControlRecord)
  private static final com.trading.ingestion.transport.ControlRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trading.ingestion.transport.ControlRecord();
  }

  public static com.trading.ingestion.transport.ControlRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ControlRecord>
      PARSER = new com.google.protobuf.AbstractParser<ControlRecord>() {
    @java.lang.Override
    public ControlRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ControlRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ControlRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trading.ingestion.transport.ControlRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

