// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

/**
 * Protobuf type {@code marketdata.MarketDataBatch}
 */
public final class MarketDataBatch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marketdata.MarketDataBatch)
    MarketDataBatchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MarketDataBatch.newBuilder() to construct.
  private MarketDataBatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MarketDataBatch() {
    connectionId_ = "";
    events_ = java.util.Collections.emptyList();
    batchPayloadHash_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MarketDataBatch();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_MarketDataBatch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_MarketDataBatch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trading.ingestion.transport.MarketDataBatch.class, com.trading.ingestion.transport.MarketDataBatch.Builder.class);
  }

  public static final int CONNECTION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object connectionId_ = "";
  /**
   * <pre>
   * "ingestion-local/hft-0"
   * </pre>
   *
   * <code>string connection_id = 1;</code>
   * @return The connectionId.
   */
  @java.lang.Override
  public java.lang.String getConnectionId() {
    java.lang.Object ref = connectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connectionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "ingestion-local/hft-0"
   * </pre>
   *
   * <code>string connection_id = 1;</code>
   * @return The bytes for connectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConnectionIdBytes() {
    java.lang.Object ref = connectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNECTION_EPOCH_FIELD_NUMBER = 2;
  private long connectionEpoch_ = 0L;
  /**
   * <pre>
   * monotonic per slot, increments per reconnect
   * </pre>
   *
   * <code>int64 connection_epoch = 2;</code>
   * @return The connectionEpoch.
   */
  @java.lang.Override
  public long getConnectionEpoch() {
    return connectionEpoch_;
  }

  public static final int BATCH_SEQ_FIELD_NUMBER = 3;
  private long batchSeq_ = 0L;
  /**
   * <pre>
   * per-connection monotonic batch counter
   * </pre>
   *
   * <code>int64 batch_seq = 3;</code>
   * @return The batchSeq.
   */
  @java.lang.Override
  public long getBatchSeq() {
    return batchSeq_;
  }

  public static final int CREATED_MS_FIELD_NUMBER = 4;
  private long createdMs_ = 0L;
  /**
   * <pre>
   * T2 (batch creation, ms epoch)
   * </pre>
   *
   * <code>int64 created_ms = 4;</code>
   * @return The createdMs.
   */
  @java.lang.Override
  public long getCreatedMs() {
    return createdMs_;
  }

  public static final int EVENTS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.trading.ingestion.transport.TickEvent> events_;
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.trading.ingestion.transport.TickEvent> getEventsList() {
    return events_;
  }
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.trading.ingestion.transport.TickEventOrBuilder> 
      getEventsOrBuilderList() {
    return events_;
  }
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  @java.lang.Override
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  @java.lang.Override
  public com.trading.ingestion.transport.TickEvent getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  @java.lang.Override
  public com.trading.ingestion.transport.TickEventOrBuilder getEventsOrBuilder(
      int index) {
    return events_.get(index);
  }

  public static final int BATCH_PAYLOAD_HASH_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString batchPayloadHash_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * sha256 over concatenated raw payloads (Q5, computed in Go)
   * </pre>
   *
   * <code>bytes batch_payload_hash = 6;</code>
   * @return The batchPayloadHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBatchPayloadHash() {
    return batchPayloadHash_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, connectionId_);
    }
    if (connectionEpoch_ != 0L) {
      output.writeInt64(2, connectionEpoch_);
    }
    if (batchSeq_ != 0L) {
      output.writeInt64(3, batchSeq_);
    }
    if (createdMs_ != 0L) {
      output.writeInt64(4, createdMs_);
    }
    for (int i = 0; i < events_.size(); i++) {
      output.writeMessage(5, events_.get(i));
    }
    if (!batchPayloadHash_.isEmpty()) {
      output.writeBytes(6, batchPayloadHash_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(connectionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, connectionId_);
    }
    if (connectionEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, connectionEpoch_);
    }
    if (batchSeq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, batchSeq_);
    }
    if (createdMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, createdMs_);
    }
    for (int i = 0; i < events_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, events_.get(i));
    }
    if (!batchPayloadHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, batchPayloadHash_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trading.ingestion.transport.MarketDataBatch)) {
      return super.equals(obj);
    }
    com.trading.ingestion.transport.MarketDataBatch other = (com.trading.ingestion.transport.MarketDataBatch) obj;

    if (!getConnectionId()
        .equals(other.getConnectionId())) return false;
    if (getConnectionEpoch()
        != other.getConnectionEpoch()) return false;
    if (getBatchSeq()
        != other.getBatchSeq()) return false;
    if (getCreatedMs()
        != other.getCreatedMs()) return false;
    if (!getEventsList()
        .equals(other.getEventsList())) return false;
    if (!getBatchPayloadHash()
        .equals(other.getBatchPayloadHash())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONNECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConnectionId().hashCode();
    hash = (37 * hash) + CONNECTION_EPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getConnectionEpoch());
    hash = (37 * hash) + BATCH_SEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBatchSeq());
    hash = (37 * hash) + CREATED_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatedMs());
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    hash = (37 * hash) + BATCH_PAYLOAD_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getBatchPayloadHash().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.MarketDataBatch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trading.ingestion.transport.MarketDataBatch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marketdata.MarketDataBatch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marketdata.MarketDataBatch)
      com.trading.ingestion.transport.MarketDataBatchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_MarketDataBatch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_MarketDataBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trading.ingestion.transport.MarketDataBatch.class, com.trading.ingestion.transport.MarketDataBatch.Builder.class);
    }

    // Construct using com.trading.ingestion.transport.MarketDataBatch.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      connectionId_ = "";
      connectionEpoch_ = 0L;
      batchSeq_ = 0L;
      createdMs_ = 0L;
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
      } else {
        events_ = null;
        eventsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      batchPayloadHash_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_MarketDataBatch_descriptor;
    }

    @java.lang.Override
    public com.trading.ingestion.transport.MarketDataBatch getDefaultInstanceForType() {
      return com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
    }

    @java.lang.Override
    public com.trading.ingestion.transport.MarketDataBatch build() {
      com.trading.ingestion.transport.MarketDataBatch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trading.ingestion.transport.MarketDataBatch buildPartial() {
      com.trading.ingestion.transport.MarketDataBatch result = new com.trading.ingestion.transport.MarketDataBatch(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.trading.ingestion.transport.MarketDataBatch result) {
      if (eventsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.events_ = events_;
      } else {
        result.events_ = eventsBuilder_.build();
      }
    }

    private void buildPartial0(com.trading.ingestion.transport.MarketDataBatch result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.connectionId_ = connectionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.connectionEpoch_ = connectionEpoch_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.batchSeq_ = batchSeq_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.createdMs_ = createdMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.batchPayloadHash_ = batchPayloadHash_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trading.ingestion.transport.MarketDataBatch) {
        return mergeFrom((com.trading.ingestion.transport.MarketDataBatch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trading.ingestion.transport.MarketDataBatch other) {
      if (other == com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance()) return this;
      if (!other.getConnectionId().isEmpty()) {
        connectionId_ = other.connectionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getConnectionEpoch() != 0L) {
        setConnectionEpoch(other.getConnectionEpoch());
      }
      if (other.getBatchSeq() != 0L) {
        setBatchSeq(other.getBatchSeq());
      }
      if (other.getCreatedMs() != 0L) {
        setCreatedMs(other.getCreatedMs());
      }
      if (eventsBuilder_ == null) {
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
      } else {
        if (!other.events_.isEmpty()) {
          if (eventsBuilder_.isEmpty()) {
            eventsBuilder_.dispose();
            eventsBuilder_ = null;
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000010);
            eventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEventsFieldBuilder() : null;
          } else {
            eventsBuilder_.addAllMessages(other.events_);
          }
        }
      }
      if (other.getBatchPayloadHash() != com.google.protobuf.ByteString.EMPTY) {
        setBatchPayloadHash(other.getBatchPayloadHash());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              connectionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              connectionEpoch_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              batchSeq_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              createdMs_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.trading.ingestion.transport.TickEvent m =
                  input.readMessage(
                      com.trading.ingestion.transport.TickEvent.parser(),
                      extensionRegistry);
              if (eventsBuilder_ == null) {
                ensureEventsIsMutable();
                events_.add(m);
              } else {
                eventsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              batchPayloadHash_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object connectionId_ = "";
    /**
     * <pre>
     * "ingestion-local/hft-0"
     * </pre>
     *
     * <code>string connection_id = 1;</code>
     * @return The connectionId.
     */
    public java.lang.String getConnectionId() {
      java.lang.Object ref = connectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "ingestion-local/hft-0"
     * </pre>
     *
     * <code>string connection_id = 1;</code>
     * @return The bytes for connectionId.
     */
    public com.google.protobuf.ByteString
        getConnectionIdBytes() {
      java.lang.Object ref = connectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "ingestion-local/hft-0"
     * </pre>
     *
     * <code>string connection_id = 1;</code>
     * @param value The connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      connectionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ingestion-local/hft-0"
     * </pre>
     *
     * <code>string connection_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionId() {
      connectionId_ = getDefaultInstance().getConnectionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ingestion-local/hft-0"
     * </pre>
     *
     * <code>string connection_id = 1;</code>
     * @param value The bytes for connectionId to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      connectionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long connectionEpoch_ ;
    /**
     * <pre>
     * monotonic per slot, increments per reconnect
     * </pre>
     *
     * <code>int64 connection_epoch = 2;</code>
     * @return The connectionEpoch.
     */
    @java.lang.Override
    public long getConnectionEpoch() {
      return connectionEpoch_;
    }
    /**
     * <pre>
     * monotonic per slot, increments per reconnect
     * </pre>
     *
     * <code>int64 connection_epoch = 2;</code>
     * @param value The connectionEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setConnectionEpoch(long value) {
      
      connectionEpoch_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * monotonic per slot, increments per reconnect
     * </pre>
     *
     * <code>int64 connection_epoch = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectionEpoch() {
      bitField0_ = (bitField0_ & ~0x00000002);
      connectionEpoch_ = 0L;
      onChanged();
      return this;
    }

    private long batchSeq_ ;
    /**
     * <pre>
     * per-connection monotonic batch counter
     * </pre>
     *
     * <code>int64 batch_seq = 3;</code>
     * @return The batchSeq.
     */
    @java.lang.Override
    public long getBatchSeq() {
      return batchSeq_;
    }
    /**
     * <pre>
     * per-connection monotonic batch counter
     * </pre>
     *
     * <code>int64 batch_seq = 3;</code>
     * @param value The batchSeq to set.
     * @return This builder for chaining.
     */
    public Builder setBatchSeq(long value) {
      
      batchSeq_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * per-connection monotonic batch counter
     * </pre>
     *
     * <code>int64 batch_seq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchSeq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      batchSeq_ = 0L;
      onChanged();
      return this;
    }

    private long createdMs_ ;
    /**
     * <pre>
     * T2 (batch creation, ms epoch)
     * </pre>
     *
     * <code>int64 created_ms = 4;</code>
     * @return The createdMs.
     */
    @java.lang.Override
    public long getCreatedMs() {
      return createdMs_;
    }
    /**
     * <pre>
     * T2 (batch creation, ms epoch)
     * </pre>
     *
     * <code>int64 created_ms = 4;</code>
     * @param value The createdMs to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedMs(long value) {
      
      createdMs_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * T2 (batch creation, ms epoch)
     * </pre>
     *
     * <code>int64 created_ms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedMs() {
      bitField0_ = (bitField0_ & ~0x00000008);
      createdMs_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.trading.ingestion.transport.TickEvent> events_ =
      java.util.Collections.emptyList();
    private void ensureEventsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        events_ = new java.util.ArrayList<com.trading.ingestion.transport.TickEvent>(events_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.trading.ingestion.transport.TickEvent, com.trading.ingestion.transport.TickEvent.Builder, com.trading.ingestion.transport.TickEventOrBuilder> eventsBuilder_;

    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public java.util.List<com.trading.ingestion.transport.TickEvent> getEventsList() {
      if (eventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(events_);
      } else {
        return eventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public int getEventsCount() {
      if (eventsBuilder_ == null) {
        return events_.size();
      } else {
        return eventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public com.trading.ingestion.transport.TickEvent getEvents(int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);
      } else {
        return eventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder setEvents(
        int index, com.trading.ingestion.transport.TickEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder setEvents(
        int index, com.trading.ingestion.transport.TickEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder addEvents(com.trading.ingestion.transport.TickEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder addEvents(
        int index, com.trading.ingestion.transport.TickEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(index, value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder addEvents(
        com.trading.ingestion.transport.TickEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder addEvents(
        int index, com.trading.ingestion.transport.TickEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder addAllEvents(
        java.lang.Iterable<? extends com.trading.ingestion.transport.TickEvent> values) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, events_);
        onChanged();
      } else {
        eventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder clearEvents() {
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public Builder removeEvents(int index) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.remove(index);
        onChanged();
      } else {
        eventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public com.trading.ingestion.transport.TickEvent.Builder getEventsBuilder(
        int index) {
      return getEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public com.trading.ingestion.transport.TickEventOrBuilder getEventsOrBuilder(
        int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);  } else {
        return eventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public java.util.List<? extends com.trading.ingestion.transport.TickEventOrBuilder> 
         getEventsOrBuilderList() {
      if (eventsBuilder_ != null) {
        return eventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(events_);
      }
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public com.trading.ingestion.transport.TickEvent.Builder addEventsBuilder() {
      return getEventsFieldBuilder().addBuilder(
          com.trading.ingestion.transport.TickEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public com.trading.ingestion.transport.TickEvent.Builder addEventsBuilder(
        int index) {
      return getEventsFieldBuilder().addBuilder(
          index, com.trading.ingestion.transport.TickEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .marketdata.TickEvent events = 5;</code>
     */
    public java.util.List<com.trading.ingestion.transport.TickEvent.Builder> 
         getEventsBuilderList() {
      return getEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.trading.ingestion.transport.TickEvent, com.trading.ingestion.transport.TickEvent.Builder, com.trading.ingestion.transport.TickEventOrBuilder> 
        getEventsFieldBuilder() {
      if (eventsBuilder_ == null) {
        eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.trading.ingestion.transport.TickEvent, com.trading.ingestion.transport.TickEvent.Builder, com.trading.ingestion.transport.TickEventOrBuilder>(
                events_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        events_ = null;
      }
      return eventsBuilder_;
    }

    private com.google.protobuf.ByteString batchPayloadHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * sha256 over concatenated raw payloads (Q5, computed in Go)
     * </pre>
     *
     * <code>bytes batch_payload_hash = 6;</code>
     * @return The batchPayloadHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBatchPayloadHash() {
      return batchPayloadHash_;
    }
    /**
     * <pre>
     * sha256 over concatenated raw payloads (Q5, computed in Go)
     * </pre>
     *
     * <code>bytes batch_payload_hash = 6;</code>
     * @param value The batchPayloadHash to set.
     * @return This builder for chaining.
     */
    public Builder setBatchPayloadHash(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      batchPayloadHash_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sha256 over concatenated raw payloads (Q5, computed in Go)
     * </pre>
     *
     * <code>bytes batch_payload_hash = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchPayloadHash() {
      bitField0_ = (bitField0_ & ~0x00000020);
      batchPayloadHash_ = getDefaultInstance().getBatchPayloadHash();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marketdata.MarketDataBatch)
  }

  // @@protoc_insertion_point(class_scope:marketdata.MarketDataBatch)
  private static final com.trading.ingestion.transport.MarketDataBatch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trading.ingestion.transport.MarketDataBatch();
  }

  public static com.trading.ingestion.transport.MarketDataBatch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MarketDataBatch>
      PARSER = new com.google.protobuf.AbstractParser<MarketDataBatch>() {
    @java.lang.Override
    public MarketDataBatch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MarketDataBatch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarketDataBatch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trading.ingestion.transport.MarketDataBatch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

