// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

public interface MarketDataBatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marketdata.MarketDataBatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "ingestion-local/hft-0"
   * </pre>
   *
   * <code>string connection_id = 1;</code>
   * @return The connectionId.
   */
  java.lang.String getConnectionId();
  /**
   * <pre>
   * "ingestion-local/hft-0"
   * </pre>
   *
   * <code>string connection_id = 1;</code>
   * @return The bytes for connectionId.
   */
  com.google.protobuf.ByteString
      getConnectionIdBytes();

  /**
   * <pre>
   * monotonic per slot, increments per reconnect
   * </pre>
   *
   * <code>int64 connection_epoch = 2;</code>
   * @return The connectionEpoch.
   */
  long getConnectionEpoch();

  /**
   * <pre>
   * per-connection monotonic batch counter
   * </pre>
   *
   * <code>int64 batch_seq = 3;</code>
   * @return The batchSeq.
   */
  long getBatchSeq();

  /**
   * <pre>
   * T2 (batch creation, ms epoch)
   * </pre>
   *
   * <code>int64 created_ms = 4;</code>
   * @return The createdMs.
   */
  long getCreatedMs();

  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  java.util.List<com.trading.ingestion.transport.TickEvent> 
      getEventsList();
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  com.trading.ingestion.transport.TickEvent getEvents(int index);
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  java.util.List<? extends com.trading.ingestion.transport.TickEventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .marketdata.TickEvent events = 5;</code>
   */
  com.trading.ingestion.transport.TickEventOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <pre>
   * sha256 over concatenated raw payloads (Q5, computed in Go)
   * </pre>
   *
   * <code>bytes batch_payload_hash = 6;</code>
   * @return The batchPayloadHash.
   */
  com.google.protobuf.ByteString getBatchPayloadHash();
}
