// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

public interface TickEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marketdata.TickEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * control / provenance
   * </pre>
   *
   * <code>string slot_id = 1;</code>
   * @return The slotId.
   */
  java.lang.String getSlotId();
  /**
   * <pre>
   * control / provenance
   * </pre>
   *
   * <code>string slot_id = 1;</code>
   * @return The bytes for slotId.
   */
  com.google.protobuf.ByteString
      getSlotIdBytes();

  /**
   * <pre>
   * "ltp" | "ltpc" | "quote" | "full"
   * </pre>
   *
   * <code>string mode = 2;</code>
   * @return The mode.
   */
  java.lang.String getMode();
  /**
   * <pre>
   * "ltp" | "ltpc" | "quote" | "full"
   * </pre>
   *
   * <code>string mode = 2;</code>
   * @return The bytes for mode.
   */
  com.google.protobuf.ByteString
      getModeBytes();

  /**
   * <pre>
   * instrument_token (Go int32 — bit-exact)
   * </pre>
   *
   * <code>int32 token = 3;</code>
   * @return The token.
   */
  int getToken();

  /**
   * <pre>
   * "hft" (Go Tick.Feed, not persisted to row but carried for parity)
   * </pre>
   *
   * <code>string feed = 29;</code>
   * @return The feed.
   */
  java.lang.String getFeed();
  /**
   * <pre>
   * "hft" (Go Tick.Feed, not persisted to row but carried for parity)
   * </pre>
   *
   * <code>string feed = 29;</code>
   * @return The bytes for feed.
   */
  com.google.protobuf.ByteString
      getFeedBytes();

  /**
   * <pre>
   * exchange timestamp (source time, preserved — Q29)
   * </pre>
   *
   * <code>int64 ts_ms = 4;</code>
   * @return The tsMs.
   */
  long getTsMs();

  /**
   * <pre>
   * T1 (Go receipt)
   * </pre>
   *
   * <code>int64 received_ms = 5;</code>
   * @return The receivedMs.
   */
  long getReceivedMs();

  /**
   * <pre>
   * P1-281: BEST-EFFORT connection-local provenance (gap evidence + logging only — FlussClientAdapter persists NO sequence column in the 21-col row; broker resets/duplicates must never be treated as authoritative downstream).
   * </pre>
   *
   * <code>int64 feed_sequence_local = 6;</code>
   * @return The feedSequenceLocal.
   */
  long getFeedSequenceLocal();

  /**
   * <pre>
   * market data — prices are integer paise, never float (doc §28)
   * </pre>
   *
   * <code>int64 ltp_paise = 7;</code>
   * @return The ltpPaise.
   */
  long getLtpPaise();

  /**
   * <code>int64 close_paise = 8;</code>
   * @return The closePaise.
   */
  long getClosePaise();

  /**
   * <code>int64 open_paise = 9;</code>
   * @return The openPaise.
   */
  long getOpenPaise();

  /**
   * <code>int64 high_paise = 10;</code>
   * @return The highPaise.
   */
  long getHighPaise();

  /**
   * <code>int64 low_paise = 11;</code>
   * @return The lowPaise.
   */
  long getLowPaise();

  /**
   * <code>int64 vwap_paise = 12;</code>
   * @return The vwapPaise.
   */
  long getVwapPaise();

  /**
   * <code>int64 ltq = 13;</code>
   * @return The ltq.
   */
  long getLtq();

  /**
   * <code>int64 volume = 14;</code>
   * @return The volume.
   */
  long getVolume();

  /**
   * <code>int64 total_buy_qty = 15;</code>
   * @return The totalBuyQty.
   */
  long getTotalBuyQty();

  /**
   * <code>int64 total_sell_qty = 16;</code>
   * @return The totalSellQty.
   */
  long getTotalSellQty();

  /**
   * <code>int64 open_interest = 17;</code>
   * @return The openInterest.
   */
  long getOpenInterest();

  /**
   * <pre>
   * fixed 5 (Q-O2)
   * </pre>
   *
   * <code>repeated int32 bid_px = 18;</code>
   * @return A list containing the bidPx.
   */
  java.util.List<java.lang.Integer> getBidPxList();
  /**
   * <pre>
   * fixed 5 (Q-O2)
   * </pre>
   *
   * <code>repeated int32 bid_px = 18;</code>
   * @return The count of bidPx.
   */
  int getBidPxCount();
  /**
   * <pre>
   * fixed 5 (Q-O2)
   * </pre>
   *
   * <code>repeated int32 bid_px = 18;</code>
   * @param index The index of the element to return.
   * @return The bidPx at the given index.
   */
  int getBidPx(int index);

  /**
   * <code>repeated int32 ask_px = 19;</code>
   * @return A list containing the askPx.
   */
  java.util.List<java.lang.Integer> getAskPxList();
  /**
   * <code>repeated int32 ask_px = 19;</code>
   * @return The count of askPx.
   */
  int getAskPxCount();
  /**
   * <code>repeated int32 ask_px = 19;</code>
   * @param index The index of the element to return.
   * @return The askPx at the given index.
   */
  int getAskPx(int index);

  /**
   * <code>repeated int32 bid_qty = 20;</code>
   * @return A list containing the bidQty.
   */
  java.util.List<java.lang.Integer> getBidQtyList();
  /**
   * <code>repeated int32 bid_qty = 20;</code>
   * @return The count of bidQty.
   */
  int getBidQtyCount();
  /**
   * <code>repeated int32 bid_qty = 20;</code>
   * @param index The index of the element to return.
   * @return The bidQty at the given index.
   */
  int getBidQty(int index);

  /**
   * <code>repeated int32 ask_qty = 21;</code>
   * @return A list containing the askQty.
   */
  java.util.List<java.lang.Integer> getAskQtyList();
  /**
   * <code>repeated int32 ask_qty = 21;</code>
   * @return The count of askQty.
   */
  int getAskQtyCount();
  /**
   * <code>repeated int32 ask_qty = 21;</code>
   * @param index The index of the element to return.
   * @return The askQty at the given index.
   */
  int getAskQty(int index);

  /**
   * <pre>
   * Go [5]uint16 — uint32 for proto3 (no uint16)
   * </pre>
   *
   * <code>repeated uint32 bid_orders = 22;</code>
   * @return A list containing the bidOrders.
   */
  java.util.List<java.lang.Integer> getBidOrdersList();
  /**
   * <pre>
   * Go [5]uint16 — uint32 for proto3 (no uint16)
   * </pre>
   *
   * <code>repeated uint32 bid_orders = 22;</code>
   * @return The count of bidOrders.
   */
  int getBidOrdersCount();
  /**
   * <pre>
   * Go [5]uint16 — uint32 for proto3 (no uint16)
   * </pre>
   *
   * <code>repeated uint32 bid_orders = 22;</code>
   * @param index The index of the element to return.
   * @return The bidOrders at the given index.
   */
  int getBidOrders(int index);

  /**
   * <code>repeated uint32 ask_orders = 23;</code>
   * @return A list containing the askOrders.
   */
  java.util.List<java.lang.Integer> getAskOrdersList();
  /**
   * <code>repeated uint32 ask_orders = 23;</code>
   * @return The count of askOrders.
   */
  int getAskOrdersCount();
  /**
   * <code>repeated uint32 ask_orders = 23;</code>
   * @param index The index of the element to return.
   * @return The askOrders at the given index.
   */
  int getAskOrders(int index);

  /**
   * <pre>
   * payload preservation (Q3, Q6) — never base64
   * P1-320: BROKER-CONTROLLED, max 241B (full-tick mode); broker packet
   * bytes pass through the bridge ungated per-event (MaxBytes is a flush
   * TARGET, not a cap — batch.go:29-30). Bounded only at frame level
   * (64MiB post-marshal gate + 1M event-count gate, see above).
   * </pre>
   *
   * <code>bytes raw_payload = 24;</code>
   * @return The rawPayload.
   */
  com.google.protobuf.ByteString getRawPayload();

  /**
   * <code>string fingerprint_version = 25;</code>
   * @return The fingerprintVersion.
   */
  java.lang.String getFingerprintVersion();
  /**
   * <code>string fingerprint_version = 25;</code>
   * @return The bytes for fingerprintVersion.
   */
  com.google.protobuf.ByteString
      getFingerprintVersionBytes();

  /**
   * <pre>
   * computed in Java (Q19); Go does NOT compute
   * </pre>
   *
   * <code>string event_fingerprint = 26;</code>
   * @return The eventFingerprint.
   */
  java.lang.String getEventFingerprint();
  /**
   * <pre>
   * computed in Java (Q19); Go does NOT compute
   * </pre>
   *
   * <code>string event_fingerprint = 26;</code>
   * @return The bytes for eventFingerprint.
   */
  com.google.protobuf.ByteString
      getEventFingerprintBytes();

  /**
   * <pre>
   * SET IN JAVA at row-build (not from Go)
   * </pre>
   *
   * <code>string decoder_version = 27;</code>
   * @return The decoderVersion.
   */
  java.lang.String getDecoderVersion();
  /**
   * <pre>
   * SET IN JAVA at row-build (not from Go)
   * </pre>
   *
   * <code>string decoder_version = 27;</code>
   * @return The bytes for decoderVersion.
   */
  com.google.protobuf.ByteString
      getDecoderVersionBytes();

  /**
   * <pre>
   * SET IN JAVA at row-build (not from Go)
   * </pre>
   *
   * <code>string protocol_version = 28;</code>
   * @return The protocolVersion.
   */
  java.lang.String getProtocolVersion();
  /**
   * <pre>
   * SET IN JAVA at row-build (not from Go)
   * </pre>
   *
   * <code>string protocol_version = 28;</code>
   * @return The bytes for protocolVersion.
   */
  com.google.protobuf.ByteString
      getProtocolVersionBytes();

  /**
   * <pre>
   * payload integrity (Q5): sha256 of raw_payload, computed ONCE in Go
   * (32 bytes); Java verifies it at tick admission before any other gate
   * (M4-6, always-on: missing -&gt; MISSING_PAYLOAD_HASH quarantine, mismatch -&gt;
   * HASH_MISMATCH, malformed length -&gt; INVALID_SCHEMA; never append)
   * </pre>
   *
   * <code>bytes payload_hash = 30;</code>
   * @return The payloadHash.
   */
  com.google.protobuf.ByteString getPayloadHash();

  /**
   * <pre>
   * T8 staged-latency timestamps (ms epoch, monotonic — never persisted,
   * transport-only provenance for the T8 latency budget):
   * </pre>
   *
   * <code>int64 go_received_ms = 31;</code>
   * @return The goReceivedMs.
   */
  long getGoReceivedMs();

  /**
   * <pre>
   * T6: Go batcher Add (before proto marshal/write)
   * </pre>
   *
   * <code>int64 go_emit_ms = 32;</code>
   * @return The goEmitMs.
   */
  long getGoEmitMs();

  /**
   * <pre>
   * --- v4: full-mode field capture. Every field below is stored as a BIGINT
   * NULL column at raw_table_1 index 33-44 (raw_table_1 indexes 21-71 in DDL
   * order). "Absent" and "0" are different facts: the optional fields carry
   * presence so the row can say NULL. The emit path decides it (marketdata
   * ToTickEvent) because that is the one place that sees both the value and the
   * feed; Java only has to honour presence. Which fields are optional is not
   * cosmetic - change_flag 0, oi_day_high 0, imbalance_qty 0 and volume_delta 0
   * are all real values, so a plain field would make "not reported" look like
   * data. Everything not marked optional is reported by BOTH feeds.
   * </pre>
   *
   * <code>optional int32 change_flag = 33;</code>
   * @return Whether the changeFlag field is set.
   */
  boolean hasChangeFlag();
  /**
   * <pre>
   * --- v4: full-mode field capture. Every field below is stored as a BIGINT
   * NULL column at raw_table_1 index 33-44 (raw_table_1 indexes 21-71 in DDL
   * order). "Absent" and "0" are different facts: the optional fields carry
   * presence so the row can say NULL. The emit path decides it (marketdata
   * ToTickEvent) because that is the one place that sees both the value and the
   * feed; Java only has to honour presence. Which fields are optional is not
   * cosmetic - change_flag 0, oi_day_high 0, imbalance_qty 0 and volume_delta 0
   * are all real values, so a plain field would make "not reported" look like
   * data. Everything not marked optional is reported by BOTH feeds.
   * </pre>
   *
   * <code>optional int32 change_flag = 33;</code>
   * @return The changeFlag.
   */
  int getChangeFlag();

  /**
   * <pre>
   * standard feed only (MarketTick.OIDayHigh)
   * </pre>
   *
   * <code>optional int64 oi_day_high = 34;</code>
   * @return Whether the oiDayHigh field is set.
   */
  boolean hasOiDayHigh();
  /**
   * <pre>
   * standard feed only (MarketTick.OIDayHigh)
   * </pre>
   *
   * <code>optional int64 oi_day_high = 34;</code>
   * @return The oiDayHigh.
   */
  long getOiDayHigh();

  /**
   * <pre>
   * standard feed only (MarketTick.OIDayLow)
   * </pre>
   *
   * <code>optional int64 oi_day_low = 35;</code>
   * @return Whether the oiDayLow field is set.
   */
  boolean hasOiDayLow();
  /**
   * <pre>
   * standard feed only (MarketTick.OIDayLow)
   * </pre>
   *
   * <code>optional int64 oi_day_low = 35;</code>
   * @return The oiDayLow.
   */
  long getOiDayLow();

  /**
   * <pre>
   * both feeds: standard LowerLimit / HFT DprL
   * </pre>
   *
   * <code>int64 lower_limit_paise = 36;</code>
   * @return The lowerLimitPaise.
   */
  long getLowerLimitPaise();

  /**
   * <pre>
   * both feeds: standard UpperLimit / HFT DprH
   * </pre>
   *
   * <code>int64 upper_limit_paise = 37;</code>
   * @return The upperLimitPaise.
   */
  long getUpperLimitPaise();

  /**
   * <pre>
   * CAS trailer trio: standard feed only, appended to every mode from ~15:15 IST.
   * optional because "no CAS frame yet" must reach the row as NULL, not as 0
   * (imbalance_qty 0 during the auction means a balanced book, which is not the
   * same fact as "outside the auction window").
   * </pre>
   *
   * <code>optional int64 imbalance_qty = 38;</code>
   * @return Whether the imbalanceQty field is set.
   */
  boolean hasImbalanceQty();
  /**
   * <pre>
   * CAS trailer trio: standard feed only, appended to every mode from ~15:15 IST.
   * optional because "no CAS frame yet" must reach the row as NULL, not as 0
   * (imbalance_qty 0 during the auction means a balanced book, which is not the
   * same fact as "outside the auction window").
   * </pre>
   *
   * <code>optional int64 imbalance_qty = 38;</code>
   * @return The imbalanceQty.
   */
  long getImbalanceQty();

  /**
   * <code>optional int64 indicative_close_paise = 39;</code>
   * @return Whether the indicativeClosePaise field is set.
   */
  boolean hasIndicativeClosePaise();
  /**
   * <code>optional int64 indicative_close_paise = 39;</code>
   * @return The indicativeClosePaise.
   */
  long getIndicativeClosePaise();

  /**
   * <code>optional int64 ref_price_paise = 40;</code>
   * @return Whether the refPricePaise field is set.
   */
  boolean hasRefPricePaise();
  /**
   * <code>optional int64 ref_price_paise = 40;</code>
   * @return The refPricePaise.
   */
  long getRefPricePaise();

  /**
   * <pre>
   * last traded time, epoch MS: normalized per feed (standard LTT is seconds, HFT is microseconds)
   * </pre>
   *
   * <code>int64 ltt_ms = 41;</code>
   * @return The lttMs.
   */
  long getLttMs();

  /**
   * <pre>
   * HFT only (average traded value)
   * </pre>
   *
   * <code>optional int64 atv = 42;</code>
   * @return Whether the atv field is set.
   */
  boolean hasAtv();
  /**
   * <pre>
   * HFT only (average traded value)
   * </pre>
   *
   * <code>optional int64 atv = 42;</code>
   * @return The atv.
   */
  long getAtv();

  /**
   * <pre>
   * HFT only (traded value)
   * </pre>
   *
   * <code>optional int64 btv = 43;</code>
   * @return Whether the btv field is set.
   */
  boolean hasBtv();
  /**
   * <pre>
   * HFT only (traded value)
   * </pre>
   *
   * <code>optional int64 btv = 43;</code>
   * @return The btv.
   */
  long getBtv();

  /**
   * <pre>
   * Per-tick traded quantity = cumulative day volume minus the previous tick's for
   * the same token. 0 = no trade happened; unset = baseline unknown (first tick of
   * the process for that token, or a counter reset). Candle volume must sum THIS;
   * summing ltq (a last-trade size) under-counts batched trades.
   * </pre>
   *
   * <code>optional int64 volume_delta = 44;</code>
   * @return Whether the volumeDelta field is set.
   */
  boolean hasVolumeDelta();
  /**
   * <pre>
   * Per-tick traded quantity = cumulative day volume minus the previous tick's for
   * the same token. 0 = no trade happened; unset = baseline unknown (first tick of
   * the process for that token, or a counter reset). Candle volume must sum THIS;
   * summing ltq (a last-trade size) under-counts batched trades.
   * </pre>
   *
   * <code>optional int64 volume_delta = 44;</code>
   * @return The volumeDelta.
   */
  long getVolumeDelta();
}
