// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

public interface TransportFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:marketdata.TransportFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
   * @return Whether the marketBatch field is set.
   */
  boolean hasMarketBatch();
  /**
   * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
   * @return The marketBatch.
   */
  com.trading.ingestion.transport.MarketDataBatch getMarketBatch();
  /**
   * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
   */
  com.trading.ingestion.transport.MarketDataBatchOrBuilder getMarketBatchOrBuilder();

  /**
   * <code>.marketdata.ControlRecord control = 2;</code>
   * @return Whether the control field is set.
   */
  boolean hasControl();
  /**
   * <code>.marketdata.ControlRecord control = 2;</code>
   * @return The control.
   */
  com.trading.ingestion.transport.ControlRecord getControl();
  /**
   * <code>.marketdata.ControlRecord control = 2;</code>
   */
  com.trading.ingestion.transport.ControlRecordOrBuilder getControlOrBuilder();

  /**
   * <pre>
   * framing version; Java rejects unknown → quarantine
   * </pre>
   *
   * <code>int32 protocol_version = 3;</code>
   * @return The protocolVersion.
   */
  int getProtocolVersion();

  public com.trading.ingestion.transport.TransportFrame.PayloadCase getPayloadCase();
}
