// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: market_data.proto

package com.trading.ingestion.transport;

/**
 * Protobuf type {@code marketdata.TransportFrame}
 */
public final class TransportFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:marketdata.TransportFrame)
    TransportFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransportFrame.newBuilder() to construct.
  private TransportFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransportFrame() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransportFrame();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_TransportFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_TransportFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trading.ingestion.transport.TransportFrame.class, com.trading.ingestion.transport.TransportFrame.Builder.class);
  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MARKET_BATCH(1),
    CONTROL(2),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return MARKET_BATCH;
        case 2: return CONTROL;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int MARKET_BATCH_FIELD_NUMBER = 1;
  /**
   * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
   * @return Whether the marketBatch field is set.
   */
  @java.lang.Override
  public boolean hasMarketBatch() {
    return payloadCase_ == 1;
  }
  /**
   * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
   * @return The marketBatch.
   */
  @java.lang.Override
  public com.trading.ingestion.transport.MarketDataBatch getMarketBatch() {
    if (payloadCase_ == 1) {
       return (com.trading.ingestion.transport.MarketDataBatch) payload_;
    }
    return com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
  }
  /**
   * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
   */
  @java.lang.Override
  public com.trading.ingestion.transport.MarketDataBatchOrBuilder getMarketBatchOrBuilder() {
    if (payloadCase_ == 1) {
       return (com.trading.ingestion.transport.MarketDataBatch) payload_;
    }
    return com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
  }

  public static final int CONTROL_FIELD_NUMBER = 2;
  /**
   * <code>.marketdata.ControlRecord control = 2;</code>
   * @return Whether the control field is set.
   */
  @java.lang.Override
  public boolean hasControl() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.marketdata.ControlRecord control = 2;</code>
   * @return The control.
   */
  @java.lang.Override
  public com.trading.ingestion.transport.ControlRecord getControl() {
    if (payloadCase_ == 2) {
       return (com.trading.ingestion.transport.ControlRecord) payload_;
    }
    return com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
  }
  /**
   * <code>.marketdata.ControlRecord control = 2;</code>
   */
  @java.lang.Override
  public com.trading.ingestion.transport.ControlRecordOrBuilder getControlOrBuilder() {
    if (payloadCase_ == 2) {
       return (com.trading.ingestion.transport.ControlRecord) payload_;
    }
    return com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
  }

  public static final int PROTOCOL_VERSION_FIELD_NUMBER = 3;
  private int protocolVersion_ = 0;
  /**
   * <pre>
   * framing version; Java rejects unknown → quarantine
   * </pre>
   *
   * <code>int32 protocol_version = 3;</code>
   * @return The protocolVersion.
   */
  @java.lang.Override
  public int getProtocolVersion() {
    return protocolVersion_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (com.trading.ingestion.transport.MarketDataBatch) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (com.trading.ingestion.transport.ControlRecord) payload_);
    }
    if (protocolVersion_ != 0) {
      output.writeInt32(3, protocolVersion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.trading.ingestion.transport.MarketDataBatch) payload_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.trading.ingestion.transport.ControlRecord) payload_);
    }
    if (protocolVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, protocolVersion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trading.ingestion.transport.TransportFrame)) {
      return super.equals(obj);
    }
    com.trading.ingestion.transport.TransportFrame other = (com.trading.ingestion.transport.TransportFrame) obj;

    if (getProtocolVersion()
        != other.getProtocolVersion()) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getMarketBatch()
            .equals(other.getMarketBatch())) return false;
        break;
      case 2:
        if (!getControl()
            .equals(other.getControl())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getProtocolVersion();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + MARKET_BATCH_FIELD_NUMBER;
        hash = (53 * hash) + getMarketBatch().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CONTROL_FIELD_NUMBER;
        hash = (53 * hash) + getControl().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trading.ingestion.transport.TransportFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.TransportFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trading.ingestion.transport.TransportFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trading.ingestion.transport.TransportFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code marketdata.TransportFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:marketdata.TransportFrame)
      com.trading.ingestion.transport.TransportFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_TransportFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_TransportFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trading.ingestion.transport.TransportFrame.class, com.trading.ingestion.transport.TransportFrame.Builder.class);
    }

    // Construct using com.trading.ingestion.transport.TransportFrame.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (marketBatchBuilder_ != null) {
        marketBatchBuilder_.clear();
      }
      if (controlBuilder_ != null) {
        controlBuilder_.clear();
      }
      protocolVersion_ = 0;
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trading.ingestion.transport.MarketDataProto.internal_static_marketdata_TransportFrame_descriptor;
    }

    @java.lang.Override
    public com.trading.ingestion.transport.TransportFrame getDefaultInstanceForType() {
      return com.trading.ingestion.transport.TransportFrame.getDefaultInstance();
    }

    @java.lang.Override
    public com.trading.ingestion.transport.TransportFrame build() {
      com.trading.ingestion.transport.TransportFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trading.ingestion.transport.TransportFrame buildPartial() {
      com.trading.ingestion.transport.TransportFrame result = new com.trading.ingestion.transport.TransportFrame(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.trading.ingestion.transport.TransportFrame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.protocolVersion_ = protocolVersion_;
      }
    }

    private void buildPartialOneofs(com.trading.ingestion.transport.TransportFrame result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1 &&
          marketBatchBuilder_ != null) {
        result.payload_ = marketBatchBuilder_.build();
      }
      if (payloadCase_ == 2 &&
          controlBuilder_ != null) {
        result.payload_ = controlBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trading.ingestion.transport.TransportFrame) {
        return mergeFrom((com.trading.ingestion.transport.TransportFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trading.ingestion.transport.TransportFrame other) {
      if (other == com.trading.ingestion.transport.TransportFrame.getDefaultInstance()) return this;
      if (other.getProtocolVersion() != 0) {
        setProtocolVersion(other.getProtocolVersion());
      }
      switch (other.getPayloadCase()) {
        case MARKET_BATCH: {
          mergeMarketBatch(other.getMarketBatch());
          break;
        }
        case CONTROL: {
          mergeControl(other.getControl());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMarketBatchFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getControlFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 24: {
              protocolVersion_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        com.trading.ingestion.transport.MarketDataBatch, com.trading.ingestion.transport.MarketDataBatch.Builder, com.trading.ingestion.transport.MarketDataBatchOrBuilder> marketBatchBuilder_;
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     * @return Whether the marketBatch field is set.
     */
    @java.lang.Override
    public boolean hasMarketBatch() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     * @return The marketBatch.
     */
    @java.lang.Override
    public com.trading.ingestion.transport.MarketDataBatch getMarketBatch() {
      if (marketBatchBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (com.trading.ingestion.transport.MarketDataBatch) payload_;
        }
        return com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return marketBatchBuilder_.getMessage();
        }
        return com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
      }
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    public Builder setMarketBatch(com.trading.ingestion.transport.MarketDataBatch value) {
      if (marketBatchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        marketBatchBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    public Builder setMarketBatch(
        com.trading.ingestion.transport.MarketDataBatch.Builder builderForValue) {
      if (marketBatchBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        marketBatchBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    public Builder mergeMarketBatch(com.trading.ingestion.transport.MarketDataBatch value) {
      if (marketBatchBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance()) {
          payload_ = com.trading.ingestion.transport.MarketDataBatch.newBuilder((com.trading.ingestion.transport.MarketDataBatch) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          marketBatchBuilder_.mergeFrom(value);
        } else {
          marketBatchBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    public Builder clearMarketBatch() {
      if (marketBatchBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        marketBatchBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    public com.trading.ingestion.transport.MarketDataBatch.Builder getMarketBatchBuilder() {
      return getMarketBatchFieldBuilder().getBuilder();
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    @java.lang.Override
    public com.trading.ingestion.transport.MarketDataBatchOrBuilder getMarketBatchOrBuilder() {
      if ((payloadCase_ == 1) && (marketBatchBuilder_ != null)) {
        return marketBatchBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (com.trading.ingestion.transport.MarketDataBatch) payload_;
        }
        return com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
      }
    }
    /**
     * <code>.marketdata.MarketDataBatch market_batch = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.trading.ingestion.transport.MarketDataBatch, com.trading.ingestion.transport.MarketDataBatch.Builder, com.trading.ingestion.transport.MarketDataBatchOrBuilder> 
        getMarketBatchFieldBuilder() {
      if (marketBatchBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = com.trading.ingestion.transport.MarketDataBatch.getDefaultInstance();
        }
        marketBatchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.trading.ingestion.transport.MarketDataBatch, com.trading.ingestion.transport.MarketDataBatch.Builder, com.trading.ingestion.transport.MarketDataBatchOrBuilder>(
                (com.trading.ingestion.transport.MarketDataBatch) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      return marketBatchBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.trading.ingestion.transport.ControlRecord, com.trading.ingestion.transport.ControlRecord.Builder, com.trading.ingestion.transport.ControlRecordOrBuilder> controlBuilder_;
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     * @return Whether the control field is set.
     */
    @java.lang.Override
    public boolean hasControl() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     * @return The control.
     */
    @java.lang.Override
    public com.trading.ingestion.transport.ControlRecord getControl() {
      if (controlBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (com.trading.ingestion.transport.ControlRecord) payload_;
        }
        return com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return controlBuilder_.getMessage();
        }
        return com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
      }
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    public Builder setControl(com.trading.ingestion.transport.ControlRecord value) {
      if (controlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        controlBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    public Builder setControl(
        com.trading.ingestion.transport.ControlRecord.Builder builderForValue) {
      if (controlBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        controlBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    public Builder mergeControl(com.trading.ingestion.transport.ControlRecord value) {
      if (controlBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != com.trading.ingestion.transport.ControlRecord.getDefaultInstance()) {
          payload_ = com.trading.ingestion.transport.ControlRecord.newBuilder((com.trading.ingestion.transport.ControlRecord) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          controlBuilder_.mergeFrom(value);
        } else {
          controlBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    public Builder clearControl() {
      if (controlBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        controlBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    public com.trading.ingestion.transport.ControlRecord.Builder getControlBuilder() {
      return getControlFieldBuilder().getBuilder();
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    @java.lang.Override
    public com.trading.ingestion.transport.ControlRecordOrBuilder getControlOrBuilder() {
      if ((payloadCase_ == 2) && (controlBuilder_ != null)) {
        return controlBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (com.trading.ingestion.transport.ControlRecord) payload_;
        }
        return com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
      }
    }
    /**
     * <code>.marketdata.ControlRecord control = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.trading.ingestion.transport.ControlRecord, com.trading.ingestion.transport.ControlRecord.Builder, com.trading.ingestion.transport.ControlRecordOrBuilder> 
        getControlFieldBuilder() {
      if (controlBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = com.trading.ingestion.transport.ControlRecord.getDefaultInstance();
        }
        controlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.trading.ingestion.transport.ControlRecord, com.trading.ingestion.transport.ControlRecord.Builder, com.trading.ingestion.transport.ControlRecordOrBuilder>(
                (com.trading.ingestion.transport.ControlRecord) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return controlBuilder_;
    }

    private int protocolVersion_ ;
    /**
     * <pre>
     * framing version; Java rejects unknown → quarantine
     * </pre>
     *
     * <code>int32 protocol_version = 3;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public int getProtocolVersion() {
      return protocolVersion_;
    }
    /**
     * <pre>
     * framing version; Java rejects unknown → quarantine
     * </pre>
     *
     * <code>int32 protocol_version = 3;</code>
     * @param value The protocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolVersion(int value) {
      
      protocolVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * framing version; Java rejects unknown → quarantine
     * </pre>
     *
     * <code>int32 protocol_version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolVersion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      protocolVersion_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:marketdata.TransportFrame)
  }

  // @@protoc_insertion_point(class_scope:marketdata.TransportFrame)
  private static final com.trading.ingestion.transport.TransportFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trading.ingestion.transport.TransportFrame();
  }

  public static com.trading.ingestion.transport.TransportFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransportFrame>
      PARSER = new com.google.protobuf.AbstractParser<TransportFrame>() {
    @java.lang.Override
    public TransportFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransportFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransportFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trading.ingestion.transport.TransportFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

