// market_data.proto — low-latency ingestion transport contract (T1)
//
// Canonical framing between the Go bridge (decoder) and the Java
// fluss-writer (persister). Field set verified 2026-08-27 against:
//   - Go  Tick  struct        (go-bridge/main.go:21)
//   - Java GoTick (Jackson)   (IngestionService.java)
//   - SDK HFTFullTick/HFTLTPTick (vendored go-arrow)
//   - FlussClientAdapter row build (which columns actually persist)
//
// Design rules (locked, do not violate):
//   - Prices are INTEGER paise. NO float anywhere in the path.
//   - raw_payload is the EXACT original broker packet bytes (never base64/JSON).
//   - decoder_version/protocol_version are SET IN JAVA at row-build
//     (FlussClientAdapter.java:174-175: "go-arrow-sdk"/""), NOT carried from Go.
//   - Per-row payload_hash computed ONCE in Go (sha256 of raw_payload).
//   - Control records (bridge_metrics/broker_quarantine/bridge_event) ride the
//     same transport, distinguishable by record_type.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: market_data.proto

package marketdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketDataBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId     string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`           // "ingestion-local/hft-0"
	ConnectionEpoch  int64                  `protobuf:"varint,2,opt,name=connection_epoch,json=connectionEpoch,proto3" json:"connection_epoch,omitempty"` // monotonic per slot, increments per reconnect
	BatchSeq         int64                  `protobuf:"varint,3,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"`                      // per-connection monotonic batch counter
	CreatedMs        int64                  `protobuf:"varint,4,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`                   // T2 (batch creation, ms epoch)
	Events           []*TickEvent           `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	BatchPayloadHash []byte                 `protobuf:"bytes,6,opt,name=batch_payload_hash,json=batchPayloadHash,proto3" json:"batch_payload_hash,omitempty"` // sha256 over concatenated raw payloads (Q5, computed in Go)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarketDataBatch) Reset() {
	*x = MarketDataBatch{}
	mi := &file_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataBatch) ProtoMessage() {}

func (x *MarketDataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataBatch.ProtoReflect.Descriptor instead.
func (*MarketDataBatch) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *MarketDataBatch) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *MarketDataBatch) GetConnectionEpoch() int64 {
	if x != nil {
		return x.ConnectionEpoch
	}
	return 0
}

func (x *MarketDataBatch) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *MarketDataBatch) GetCreatedMs() int64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

func (x *MarketDataBatch) GetEvents() []*TickEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *MarketDataBatch) GetBatchPayloadHash() []byte {
	if x != nil {
		return x.BatchPayloadHash
	}
	return nil
}

type TickEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// control / provenance
	SlotId            string `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Mode              string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                                                       // "ltp" | "ltpc" | "quote" | "full"
	Token             int32  `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`                                                    // instrument_token (Go int32 — bit-exact)
	Feed              string `protobuf:"bytes,29,opt,name=feed,proto3" json:"feed,omitempty"`                                                      // "hft" (Go Tick.Feed, not persisted to row but carried for parity)
	TsMs              int64  `protobuf:"varint,4,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`                                          // exchange timestamp (source time, preserved — Q29)
	ReceivedMs        int64  `protobuf:"varint,5,opt,name=received_ms,json=receivedMs,proto3" json:"received_ms,omitempty"`                        // T1 (Go receipt)
	FeedSequenceLocal int64  `protobuf:"varint,6,opt,name=feed_sequence_local,json=feedSequenceLocal,proto3" json:"feed_sequence_local,omitempty"` // connection-local sequence (Q15: verify packet has real seq first)
	// market data — prices are integer paise, never float (doc §28)
	LtpPaise     int64    `protobuf:"varint,7,opt,name=ltp_paise,json=ltpPaise,proto3" json:"ltp_paise,omitempty"`
	ClosePaise   int64    `protobuf:"varint,8,opt,name=close_paise,json=closePaise,proto3" json:"close_paise,omitempty"`
	OpenPaise    int64    `protobuf:"varint,9,opt,name=open_paise,json=openPaise,proto3" json:"open_paise,omitempty"`
	HighPaise    int64    `protobuf:"varint,10,opt,name=high_paise,json=highPaise,proto3" json:"high_paise,omitempty"`
	LowPaise     int64    `protobuf:"varint,11,opt,name=low_paise,json=lowPaise,proto3" json:"low_paise,omitempty"`
	VwapPaise    int64    `protobuf:"varint,12,opt,name=vwap_paise,json=vwapPaise,proto3" json:"vwap_paise,omitempty"`
	Ltq          int64    `protobuf:"varint,13,opt,name=ltq,proto3" json:"ltq,omitempty"`
	Volume       int64    `protobuf:"varint,14,opt,name=volume,proto3" json:"volume,omitempty"`
	TotalBuyQty  int64    `protobuf:"varint,15,opt,name=total_buy_qty,json=totalBuyQty,proto3" json:"total_buy_qty,omitempty"`
	TotalSellQty int64    `protobuf:"varint,16,opt,name=total_sell_qty,json=totalSellQty,proto3" json:"total_sell_qty,omitempty"`
	OpenInterest int64    `protobuf:"varint,17,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	BidPx        []int32  `protobuf:"varint,18,rep,packed,name=bid_px,json=bidPx,proto3" json:"bid_px,omitempty"` // fixed 5 (Q-O2)
	AskPx        []int32  `protobuf:"varint,19,rep,packed,name=ask_px,json=askPx,proto3" json:"ask_px,omitempty"`
	BidQty       []int32  `protobuf:"varint,20,rep,packed,name=bid_qty,json=bidQty,proto3" json:"bid_qty,omitempty"`
	AskQty       []int32  `protobuf:"varint,21,rep,packed,name=ask_qty,json=askQty,proto3" json:"ask_qty,omitempty"`
	BidOrders    []uint32 `protobuf:"varint,22,rep,packed,name=bid_orders,json=bidOrders,proto3" json:"bid_orders,omitempty"` // Go [5]uint16 — uint32 for proto3 (no uint16)
	AskOrders    []uint32 `protobuf:"varint,23,rep,packed,name=ask_orders,json=askOrders,proto3" json:"ask_orders,omitempty"`
	// payload preservation (Q3, Q6) — never base64
	RawPayload         []byte `protobuf:"bytes,24,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"` // EXACT original broker packet bytes
	FingerprintVersion string `protobuf:"bytes,25,opt,name=fingerprint_version,json=fingerprintVersion,proto3" json:"fingerprint_version,omitempty"`
	EventFingerprint   string `protobuf:"bytes,26,opt,name=event_fingerprint,json=eventFingerprint,proto3" json:"event_fingerprint,omitempty"` // computed in Java (Q19); Go does NOT compute
	DecoderVersion     string `protobuf:"bytes,27,opt,name=decoder_version,json=decoderVersion,proto3" json:"decoder_version,omitempty"`       // SET IN JAVA at row-build (not from Go)
	ProtocolVersion    string `protobuf:"bytes,28,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`    // SET IN JAVA at row-build (not from Go)
	// payload integrity (Q5): sha256 of raw_payload, computed ONCE in Go
	PayloadHash []byte `protobuf:"bytes,30,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	// T8 staged-latency timestamps (ms epoch, monotonic — never persisted,
	// transport-only provenance for the T8 latency budget):
	GoReceivedMs  int64 `protobuf:"varint,31,opt,name=go_received_ms,json=goReceivedMs,proto3" json:"go_received_ms,omitempty"` // T1: Go bridge receipt (source of received_ms)
	GoEmitMs      int64 `protobuf:"varint,32,opt,name=go_emit_ms,json=goEmitMs,proto3" json:"go_emit_ms,omitempty"`             // T6: Go batcher Add (before proto marshal/write)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickEvent) Reset() {
	*x = TickEvent{}
	mi := &file_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickEvent) ProtoMessage() {}

func (x *TickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickEvent.ProtoReflect.Descriptor instead.
func (*TickEvent) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *TickEvent) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *TickEvent) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TickEvent) GetToken() int32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *TickEvent) GetFeed() string {
	if x != nil {
		return x.Feed
	}
	return ""
}

func (x *TickEvent) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *TickEvent) GetReceivedMs() int64 {
	if x != nil {
		return x.ReceivedMs
	}
	return 0
}

func (x *TickEvent) GetFeedSequenceLocal() int64 {
	if x != nil {
		return x.FeedSequenceLocal
	}
	return 0
}

func (x *TickEvent) GetLtpPaise() int64 {
	if x != nil {
		return x.LtpPaise
	}
	return 0
}

func (x *TickEvent) GetClosePaise() int64 {
	if x != nil {
		return x.ClosePaise
	}
	return 0
}

func (x *TickEvent) GetOpenPaise() int64 {
	if x != nil {
		return x.OpenPaise
	}
	return 0
}

func (x *TickEvent) GetHighPaise() int64 {
	if x != nil {
		return x.HighPaise
	}
	return 0
}

func (x *TickEvent) GetLowPaise() int64 {
	if x != nil {
		return x.LowPaise
	}
	return 0
}

func (x *TickEvent) GetVwapPaise() int64 {
	if x != nil {
		return x.VwapPaise
	}
	return 0
}

func (x *TickEvent) GetLtq() int64 {
	if x != nil {
		return x.Ltq
	}
	return 0
}

func (x *TickEvent) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TickEvent) GetTotalBuyQty() int64 {
	if x != nil {
		return x.TotalBuyQty
	}
	return 0
}

func (x *TickEvent) GetTotalSellQty() int64 {
	if x != nil {
		return x.TotalSellQty
	}
	return 0
}

func (x *TickEvent) GetOpenInterest() int64 {
	if x != nil {
		return x.OpenInterest
	}
	return 0
}

func (x *TickEvent) GetBidPx() []int32 {
	if x != nil {
		return x.BidPx
	}
	return nil
}

func (x *TickEvent) GetAskPx() []int32 {
	if x != nil {
		return x.AskPx
	}
	return nil
}

func (x *TickEvent) GetBidQty() []int32 {
	if x != nil {
		return x.BidQty
	}
	return nil
}

func (x *TickEvent) GetAskQty() []int32 {
	if x != nil {
		return x.AskQty
	}
	return nil
}

func (x *TickEvent) GetBidOrders() []uint32 {
	if x != nil {
		return x.BidOrders
	}
	return nil
}

func (x *TickEvent) GetAskOrders() []uint32 {
	if x != nil {
		return x.AskOrders
	}
	return nil
}

func (x *TickEvent) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *TickEvent) GetFingerprintVersion() string {
	if x != nil {
		return x.FingerprintVersion
	}
	return ""
}

func (x *TickEvent) GetEventFingerprint() string {
	if x != nil {
		return x.EventFingerprint
	}
	return ""
}

func (x *TickEvent) GetDecoderVersion() string {
	if x != nil {
		return x.DecoderVersion
	}
	return ""
}

func (x *TickEvent) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *TickEvent) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *TickEvent) GetGoReceivedMs() int64 {
	if x != nil {
		return x.GoReceivedMs
	}
	return 0
}

func (x *TickEvent) GetGoEmitMs() int64 {
	if x != nil {
		return x.GoEmitMs
	}
	return 0
}

type ControlRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RecordType           string                 `protobuf:"bytes,1,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`                 // "bridge_metrics" | "broker_quarantine" | "bridge_event"
	ContractVersion      int32                  `protobuf:"varint,2,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"` // Java rejects unknown versions → quarantine
	Event                string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	SlotId               string                 `protobuf:"bytes,4,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ConnectionId         string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ConnectionEpoch      int64                  `protobuf:"varint,6,opt,name=connection_epoch,json=connectionEpoch,proto3" json:"connection_epoch,omitempty"`
	State                string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	AssignedTokens       int32                  `protobuf:"varint,8,opt,name=assigned_tokens,json=assignedTokens,proto3" json:"assigned_tokens,omitempty"`
	AcknowledgedTokens   int32                  `protobuf:"varint,9,opt,name=acknowledged_tokens,json=acknowledgedTokens,proto3" json:"acknowledged_tokens,omitempty"`
	RejectedTokens       int32                  `protobuf:"varint,10,opt,name=rejected_tokens,json=rejectedTokens,proto3" json:"rejected_tokens,omitempty"`
	Reason               string                 `protobuf:"bytes,11,opt,name=reason,proto3" json:"reason,omitempty"`
	ReceivedTsMs         int64                  `protobuf:"varint,12,opt,name=received_ts_ms,json=receivedTsMs,proto3" json:"received_ts_ms,omitempty"`
	ManifestFingerprint  string                 `protobuf:"bytes,13,opt,name=manifest_fingerprint,json=manifestFingerprint,proto3" json:"manifest_fingerprint,omitempty"`
	AssignedTokenSetHash string                 `protobuf:"bytes,14,opt,name=assigned_token_set_hash,json=assignedTokenSetHash,proto3" json:"assigned_token_set_hash,omitempty"` // slot-identity safety contract
	// bridge_metrics extension
	ReconnectConsecutive int32 `protobuf:"varint,15,opt,name=reconnect_consecutive,json=reconnectConsecutive,proto3" json:"reconnect_consecutive,omitempty"`
	ActiveSockets        int32 `protobuf:"varint,16,opt,name=active_sockets,json=activeSockets,proto3" json:"active_sockets,omitempty"`
	GoGoroutines         int32 `protobuf:"varint,17,opt,name=go_goroutines,json=goGoroutines,proto3" json:"go_goroutines,omitempty"`
	TsMs                 int64 `protobuf:"varint,18,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	// broker_quarantine extension
	RawPayload    []byte `protobuf:"bytes,19,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	BrokerError   string `protobuf:"bytes,20,opt,name=broker_error,json=brokerError,proto3" json:"broker_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRecord) Reset() {
	*x = ControlRecord{}
	mi := &file_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRecord) ProtoMessage() {}

func (x *ControlRecord) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRecord.ProtoReflect.Descriptor instead.
func (*ControlRecord) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *ControlRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *ControlRecord) GetContractVersion() int32 {
	if x != nil {
		return x.ContractVersion
	}
	return 0
}

func (x *ControlRecord) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ControlRecord) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ControlRecord) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ControlRecord) GetConnectionEpoch() int64 {
	if x != nil {
		return x.ConnectionEpoch
	}
	return 0
}

func (x *ControlRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ControlRecord) GetAssignedTokens() int32 {
	if x != nil {
		return x.AssignedTokens
	}
	return 0
}

func (x *ControlRecord) GetAcknowledgedTokens() int32 {
	if x != nil {
		return x.AcknowledgedTokens
	}
	return 0
}

func (x *ControlRecord) GetRejectedTokens() int32 {
	if x != nil {
		return x.RejectedTokens
	}
	return 0
}

func (x *ControlRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ControlRecord) GetReceivedTsMs() int64 {
	if x != nil {
		return x.ReceivedTsMs
	}
	return 0
}

func (x *ControlRecord) GetManifestFingerprint() string {
	if x != nil {
		return x.ManifestFingerprint
	}
	return ""
}

func (x *ControlRecord) GetAssignedTokenSetHash() string {
	if x != nil {
		return x.AssignedTokenSetHash
	}
	return ""
}

func (x *ControlRecord) GetReconnectConsecutive() int32 {
	if x != nil {
		return x.ReconnectConsecutive
	}
	return 0
}

func (x *ControlRecord) GetActiveSockets() int32 {
	if x != nil {
		return x.ActiveSockets
	}
	return 0
}

func (x *ControlRecord) GetGoGoroutines() int32 {
	if x != nil {
		return x.GoGoroutines
	}
	return 0
}

func (x *ControlRecord) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *ControlRecord) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *ControlRecord) GetBrokerError() string {
	if x != nil {
		return x.BrokerError
	}
	return ""
}

type TransportFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TransportFrame_MarketBatch
	//	*TransportFrame_Control
	Payload         isTransportFrame_Payload `protobuf_oneof:"payload"`
	ProtocolVersion int32                    `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // framing version; Java rejects unknown → quarantine
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransportFrame) Reset() {
	*x = TransportFrame{}
	mi := &file_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportFrame) ProtoMessage() {}

func (x *TransportFrame) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportFrame.ProtoReflect.Descriptor instead.
func (*TransportFrame) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *TransportFrame) GetPayload() isTransportFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransportFrame) GetMarketBatch() *MarketDataBatch {
	if x != nil {
		if x, ok := x.Payload.(*TransportFrame_MarketBatch); ok {
			return x.MarketBatch
		}
	}
	return nil
}

func (x *TransportFrame) GetControl() *ControlRecord {
	if x != nil {
		if x, ok := x.Payload.(*TransportFrame_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *TransportFrame) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type isTransportFrame_Payload interface {
	isTransportFrame_Payload()
}

type TransportFrame_MarketBatch struct {
	MarketBatch *MarketDataBatch `protobuf:"bytes,1,opt,name=market_batch,json=marketBatch,proto3,oneof"`
}

type TransportFrame_Control struct {
	Control *ControlRecord `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*TransportFrame_MarketBatch) isTransportFrame_Payload() {}

func (*TransportFrame_Control) isTransportFrame_Payload() {}

var File_market_data_proto protoreflect.FileDescriptor

const file_market_data_proto_rawDesc = "" +
	"\n" +
	"\x11market_data.proto\x12\n" +
	"marketdata\"\xfa\x01\n" +
	"\x0fMarketDataBatch\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12)\n" +
	"\x10connection_epoch\x18\x02 \x01(\x03R\x0fconnectionEpoch\x12\x1b\n" +
	"\tbatch_seq\x18\x03 \x01(\x03R\bbatchSeq\x12\x1d\n" +
	"\n" +
	"created_ms\x18\x04 \x01(\x03R\tcreatedMs\x12-\n" +
	"\x06events\x18\x05 \x03(\v2\x15.marketdata.TickEventR\x06events\x12,\n" +
	"\x12batch_payload_hash\x18\x06 \x01(\fR\x10batchPayloadHash\"\xf1\a\n" +
	"\tTickEvent\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x14\n" +
	"\x05token\x18\x03 \x01(\x05R\x05token\x12\x12\n" +
	"\x04feed\x18\x1d \x01(\tR\x04feed\x12\x13\n" +
	"\x05ts_ms\x18\x04 \x01(\x03R\x04tsMs\x12\x1f\n" +
	"\vreceived_ms\x18\x05 \x01(\x03R\n" +
	"receivedMs\x12.\n" +
	"\x13feed_sequence_local\x18\x06 \x01(\x03R\x11feedSequenceLocal\x12\x1b\n" +
	"\tltp_paise\x18\a \x01(\x03R\bltpPaise\x12\x1f\n" +
	"\vclose_paise\x18\b \x01(\x03R\n" +
	"closePaise\x12\x1d\n" +
	"\n" +
	"open_paise\x18\t \x01(\x03R\topenPaise\x12\x1d\n" +
	"\n" +
	"high_paise\x18\n" +
	" \x01(\x03R\thighPaise\x12\x1b\n" +
	"\tlow_paise\x18\v \x01(\x03R\blowPaise\x12\x1d\n" +
	"\n" +
	"vwap_paise\x18\f \x01(\x03R\tvwapPaise\x12\x10\n" +
	"\x03ltq\x18\r \x01(\x03R\x03ltq\x12\x16\n" +
	"\x06volume\x18\x0e \x01(\x03R\x06volume\x12\"\n" +
	"\rtotal_buy_qty\x18\x0f \x01(\x03R\vtotalBuyQty\x12$\n" +
	"\x0etotal_sell_qty\x18\x10 \x01(\x03R\ftotalSellQty\x12#\n" +
	"\ropen_interest\x18\x11 \x01(\x03R\fopenInterest\x12\x15\n" +
	"\x06bid_px\x18\x12 \x03(\x05R\x05bidPx\x12\x15\n" +
	"\x06ask_px\x18\x13 \x03(\x05R\x05askPx\x12\x17\n" +
	"\abid_qty\x18\x14 \x03(\x05R\x06bidQty\x12\x17\n" +
	"\aask_qty\x18\x15 \x03(\x05R\x06askQty\x12\x1d\n" +
	"\n" +
	"bid_orders\x18\x16 \x03(\rR\tbidOrders\x12\x1d\n" +
	"\n" +
	"ask_orders\x18\x17 \x03(\rR\taskOrders\x12\x1f\n" +
	"\vraw_payload\x18\x18 \x01(\fR\n" +
	"rawPayload\x12/\n" +
	"\x13fingerprint_version\x18\x19 \x01(\tR\x12fingerprintVersion\x12+\n" +
	"\x11event_fingerprint\x18\x1a \x01(\tR\x10eventFingerprint\x12'\n" +
	"\x0fdecoder_version\x18\x1b \x01(\tR\x0edecoderVersion\x12)\n" +
	"\x10protocol_version\x18\x1c \x01(\tR\x0fprotocolVersion\x12!\n" +
	"\fpayload_hash\x18\x1e \x01(\fR\vpayloadHash\x12$\n" +
	"\x0ego_received_ms\x18\x1f \x01(\x03R\fgoReceivedMs\x12\x1c\n" +
	"\n" +
	"go_emit_ms\x18  \x01(\x03R\bgoEmitMs\"\xf5\x05\n" +
	"\rControlRecord\x12\x1f\n" +
	"\vrecord_type\x18\x01 \x01(\tR\n" +
	"recordType\x12)\n" +
	"\x10contract_version\x18\x02 \x01(\x05R\x0fcontractVersion\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\x12\x17\n" +
	"\aslot_id\x18\x04 \x01(\tR\x06slotId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12)\n" +
	"\x10connection_epoch\x18\x06 \x01(\x03R\x0fconnectionEpoch\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12'\n" +
	"\x0fassigned_tokens\x18\b \x01(\x05R\x0eassignedTokens\x12/\n" +
	"\x13acknowledged_tokens\x18\t \x01(\x05R\x12acknowledgedTokens\x12'\n" +
	"\x0frejected_tokens\x18\n" +
	" \x01(\x05R\x0erejectedTokens\x12\x16\n" +
	"\x06reason\x18\v \x01(\tR\x06reason\x12$\n" +
	"\x0ereceived_ts_ms\x18\f \x01(\x03R\freceivedTsMs\x121\n" +
	"\x14manifest_fingerprint\x18\r \x01(\tR\x13manifestFingerprint\x125\n" +
	"\x17assigned_token_set_hash\x18\x0e \x01(\tR\x14assignedTokenSetHash\x123\n" +
	"\x15reconnect_consecutive\x18\x0f \x01(\x05R\x14reconnectConsecutive\x12%\n" +
	"\x0eactive_sockets\x18\x10 \x01(\x05R\ractiveSockets\x12#\n" +
	"\rgo_goroutines\x18\x11 \x01(\x05R\fgoGoroutines\x12\x13\n" +
	"\x05ts_ms\x18\x12 \x01(\x03R\x04tsMs\x12\x1f\n" +
	"\vraw_payload\x18\x13 \x01(\fR\n" +
	"rawPayload\x12!\n" +
	"\fbroker_error\x18\x14 \x01(\tR\vbrokerError\"\xbf\x01\n" +
	"\x0eTransportFrame\x12@\n" +
	"\fmarket_batch\x18\x01 \x01(\v2\x1b.marketdata.MarketDataBatchH\x00R\vmarketBatch\x125\n" +
	"\acontrol\x18\x02 \x01(\v2\x19.marketdata.ControlRecordH\x00R\acontrol\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\x05R\x0fprotocolVersionB\t\n" +
	"\apayloadBk\n" +
	"\x1fcom.trading.ingestion.transportB\x0fMarketDataProtoP\x01Z5github.com/trading/arrow-bridge/marketdata;marketdatab\x06proto3"

var (
	file_market_data_proto_rawDescOnce sync.Once
	file_market_data_proto_rawDescData []byte
)

func file_market_data_proto_rawDescGZIP() []byte {
	file_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)))
	})
	return file_market_data_proto_rawDescData
}

var file_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_market_data_proto_goTypes = []any{
	(*MarketDataBatch)(nil), // 0: marketdata.MarketDataBatch
	(*TickEvent)(nil),       // 1: marketdata.TickEvent
	(*ControlRecord)(nil),   // 2: marketdata.ControlRecord
	(*TransportFrame)(nil),  // 3: marketdata.TransportFrame
}
var file_market_data_proto_depIdxs = []int32{
	1, // 0: marketdata.MarketDataBatch.events:type_name -> marketdata.TickEvent
	0, // 1: marketdata.TransportFrame.market_batch:type_name -> marketdata.MarketDataBatch
	2, // 2: marketdata.TransportFrame.control:type_name -> marketdata.ControlRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_market_data_proto_init() }
func file_market_data_proto_init() {
	if File_market_data_proto != nil {
		return
	}
	file_market_data_proto_msgTypes[3].OneofWrappers = []any{
		(*TransportFrame_MarketBatch)(nil),
		(*TransportFrame_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_proto_depIdxs,
		MessageInfos:      file_market_data_proto_msgTypes,
	}.Build()
	File_market_data_proto = out.File
	file_market_data_proto_goTypes = nil
	file_market_data_proto_depIdxs = nil
}
